import type { LearningInteraction, ProductionModule } from "@/lib/learning/interactionTypes";
import {
  accessibility,
  buildScene,
  caseSpec,
  compactInteraction,
  feedback,
  handoff,
  responsiveLayout,
  sceneCopy,
  sources,
  tutorContract,
} from "@/lib/learning/modules/m04M06ModuleHelpers";

const focus = "Mark every atrial event and every ventricular event before naming the relationship.";

const s0Feedback = feedback({
  correct: "Yes. Strip A contains an early atrial beat; Strip B contains an on-time P wave with no following QRS. Timing evidence comes before a block label.",
  partial: "You found the missing QRS, but one clock is incomplete. Mark every visible P and QRS so the relationship is demonstrated, not guessed.",
  incorrect: "Strip A’s unusual P arrives early. That supports atrial ectopy, not a dropped on-time sinus impulse. Re-march the P waves.",
  unsafe: "Pause at the tracing. This checkpoint grades ECG evidence, not a treatment order. Mark the atrial and ventricular clocks first.",
  notAssessable: "These teaching strips were selected because the target P waves and QRS complexes are readable. ‘Not assessable’ does not fit this case.",
  evidenceCue: "Ignore QRS for one pass and extend the P-wave march through the pause.",
});

const s0Interactions: LearningInteraction[] = [
  {
    id: "m04-s0-p-march",
    kind: "march",
    prompt: "Mark both clocks. Start with every P wave.",
    instructions: "Place at least six atrial markers and extend the expected sinus march through the unusual beat.",
    subskills: ["localize", "discriminate"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    target: "p_waves",
    minimumMarkers: 6,
    expectedPattern: "regular",
    toleranceMs: 60,
    feedback: s0Feedback,
    accessibility: accessibility({
      instructions: "Mark P-wave centers across the strip.",
      keyboard: "Choose each atrial event from the timing table or use arrow keys and Enter on the strip.",
      summary: "A timing row containing every visible atrial event and its expected-cycle relationship.",
    }),
  },
  compactInteraction({
    id: "m04-s0-p-qrs-pairing",
    kind: "pairing",
    prompt: "Pair each atrial event with its ventricular response—or with no response.",
    instructions: "Use the completed marches; do not infer a block label from the pairings alone.",
    subskills: ["discriminate"],
    left: [{ id: "p1", label: "P1" }, { id: "p2", label: "P2" }, { id: "p3", label: "P3" }, { id: "p4", label: "P4" }, { id: "p5", label: "P5" }],
    right: [{ id: "q1", label: "QRS1" }, { id: "q2", label: "QRS2" }, { id: "q3", label: "QRS3" }, { id: "no-response", label: "No ventricular response" }, { id: "q4", label: "QRS4" }],
    correctPairs: { p1: "q1", p2: "q2", p3: "q3", p4: "no-response", p5: "q4" },
    feedback: s0Feedback,
    accessibility: accessibility({ instructions: "Pair five atrial events to QRS events or no response.", keyboard: "Choose one response for each P-wave row.", summary: "Five P–QRS relationship rows, including one on-time P with no ventricular response." }),
  }),
  {
    id: "m04-s0-qrs-march",
    kind: "march",
    prompt: "Now mark every QRS complex and compare the two clocks.",
    instructions: "Place ventricular markers without moving the atrial march.",
    subskills: ["localize", "discriminate"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    target: "qrs_complexes",
    minimumMarkers: 5,
    expectedPattern: "variable",
    toleranceMs: 45,
    feedback: s0Feedback,
    accessibility: accessibility({
      instructions: "Mark QRS onsets while preserving the P-wave row.",
      keyboard: "Select ventricular events from the structured event list.",
      summary: "Separate atrial and ventricular rows reveal one atrial event without a ventricular response.",
    }),
  },
  {
    id: "m04-s0-nonconducted-point",
    kind: "point",
    prompt: "Point to the on-time P wave without a QRS.",
    instructions: "Select the atrial event that lands on the sinus march and is not followed by ventricular activation.",
    subskills: ["localize", "discriminate"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    concept: "nonconducted_on_time_p_wave",
    gradePrompt: "Grade against the case-packet nonconducted P-wave point after both marches are complete.",
    allowedLeads: ["II", "V1"],
    feedback: s0Feedback,
    accessibility: accessibility({
      instructions: "Select the nonconducted atrial event.",
      keyboard: "Choose an event number in the atrial timing row.",
      summary: "The correct event is an on-time P wave with no following QRS.",
    }),
  },
];

const s1Feedback = feedback({
  correct: "Correct. Changing AV delay lengthens PR; changing ventricular spread widens QRS. The measurements answer different questions.",
  partial: "You reached one target, but the other mechanism or boundary is incomplete. Reset and isolate one pathway.",
  incorrect: "Follow the boundaries: PR is P onset to QRS onset; QRS width is QRS onset to QRS end. Predict again before moving the control.",
  unsafe: "Pause at the model. This checkpoint grades interval physiology, not treatment. Isolate AV delay and ventricular spread.",
  notAssessable: "This is a deterministic teaching model with exact boundaries. Both intervals are assessable here.",
  evidenceCue: "Changing the relay delay moves QRS onset; changing ventricular spread stretches QRS itself.",
});

const s1Interactions: LearningInteraction[] = [
  compactInteraction({
    id: "m04-s1-av-model",
    kind: "model_explore",
    prompt: "Explore the relay and ventricular-spread model before measuring it.",
    instructions: "Visit normal conduction, longer AV delay, slower ventricular spread, and reset.",
    subskills: ["explain_mechanism"],
    model: "av_ladder",
    frames: [
      { id: "normal", label: "Normal relay", narration: "The AV node delays briefly, then His–Purkinje activation is rapid.", activeRegion: "av_node" },
      { id: "long-pr", label: "Longer AV delay", narration: "QRS onset moves later while QRS width stays unchanged.", activeRegion: "av_node" },
      { id: "wide-qrs", label: "Slower ventricular spread", narration: "QRS stretches while the AV delay stays unchanged.", activeRegion: "his_purkinje" },
      { id: "reset", label: "Reset model", narration: "Both measurements return to their baseline values." },
    ],
    requiredFrameIds: ["normal", "long-pr", "wide-qrs", "reset"],
    feedback: s1Feedback,
    accessibility: accessibility({ instructions: "Visit four static conduction-model frames.", keyboard: "Use Previous step and Next step.", summary: "Normal conduction, isolated longer AV delay, isolated slower ventricular spread, then reset." }),
  }),
  {
    id: "m04-s1-pr-model",
    kind: "caliper",
    prompt: "Increase only AV delay until PR reaches 240 ms.",
    instructions: "Predict Change PR, adjust the AV-node model, then span P onset to QRS onset.",
    subskills: ["measure", "explain_mechanism"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    measurement: "pr",
    target: { source: "authored_simulation", valueMs: 240, toleranceMs: 10, lead: "II" },
    requireBoundaryLabels: true,
    feedback: s1Feedback,
    accessibility: accessibility({
      instructions: "Set and measure a 240 millisecond PR interval in the AV-delay model.",
      keyboard: "Use ten-millisecond step buttons, then place labeled P-onset and QRS-onset calipers.",
      summary: "Longer AV delay moves QRS onset later while QRS width stays unchanged.",
    }),
  },
  {
    id: "m04-s1-qrs-model",
    kind: "caliper",
    prompt: "Reset, then slow only ventricular spread until QRS reaches 150 ms.",
    instructions: "Predict Change QRS, adjust ventricular spread, then span QRS onset to final return to baseline.",
    subskills: ["measure", "explain_mechanism"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    measurement: "qrs",
    target: { source: "authored_simulation", valueMs: 150, toleranceMs: 10, lead: "II" },
    requireBoundaryLabels: true,
    feedback: s1Feedback,
    accessibility: accessibility({
      instructions: "Set and measure a 150 millisecond QRS in the ventricular-spread model.",
      keyboard: "Use ten-millisecond step buttons, then place labeled QRS-onset and QRS-end calipers.",
      summary: "Slower ventricular spread widens QRS while AV delay stays unchanged.",
    }),
  },
];

const s2Feedback = feedback({
  correct: "Measured across beats, the conducted PR pattern is correctly identified as constant, progressive, or without a stable relationship.",
  partial: "Your category may fit, but one boundary is measured from the P peak instead of P onset. Correct the boundary before the evidence row counts.",
  incorrect: "A variable apparent PR is not the same as progressive lengthening. Re-march P waves and QRS complexes separately.",
  unsafe: "Pause at the tracing. This checkpoint grades beat-to-beat conduction evidence, not treatment. Complete the PR row.",
  notAssessable: "Use ‘not assessable’ only when the case contract declares the P onset obscured; the core strips provide readable boundaries.",
  evidenceCue: "Measure the same boundaries on every conducted beat and inspect the direction of change.",
});

const s2Interactions: LearningInteraction[] = [
  {
    id: "m04-s2-pr-calipers",
    kind: "caliper",
    prompt: "Measure each conducted PR, then name the beat-to-beat pattern.",
    instructions: "Use P onset and QRS onset in the same lead; repeat on at least four conducted beats.",
    subskills: ["measure", "discriminate"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    measurement: "pr",
    target: { source: "packet_measurement", measurementKey: "pr_ms", toleranceMs: 30, lead: "II" },
    requireBoundaryLabels: true,
    feedback: s2Feedback,
    accessibility: accessibility({
      instructions: "Enter P onset and QRS onset for each conducted beat.",
      keyboard: "Use the beat table and millisecond steppers; the PR column calculates automatically.",
      summary: "A beat table compares conducted PR intervals across the rhythm strip.",
    }),
  },
  {
    id: "m04-s2-pr-pattern",
    kind: "compare",
    prompt: "Compare the three PR rows: constant, progressively changing, and no stable relationship.",
    instructions: "Assign the measured row, not the visual pause, to the correct pattern.",
    subskills: ["discriminate", "synthesize"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    leftCaseConcept: "constant_or_progressive_pr",
    rightCaseConcept: "av_dissociation",
    dimensions: [
      { id: "ordered-change", label: "Conducted PR behavior", leftAnswer: "constant or progressively ordered", rightAnswer: "no stable PR relationship" },
      { id: "phase-lock", label: "P–QRS phase lock", leftAnswer: "present in conducted beats", rightAnswer: "absent" },
    ],
    feedback: s2Feedback,
    accessibility: accessibility({
      instructions: "Complete a two-column comparison of conducted PR behavior.",
      keyboard: "Use labeled text fields for each comparison dimension.",
      summary: "One side preserves an ordered conducted relationship; AV dissociation does not.",
    }),
  },
];

const s3Feedback = feedback({
  correct: "Yes: 1:1 conduction, PR [mean PR] ms, and a constant conducted PR. That supports first-degree AV block.",
  partial: "The PR is long, but the label also requires 1:1 conduction and consistency. Link the remaining beats.",
  incorrect: "No QRS is dropped here. Every P conducts; measure more than five small boxes from P onset to QRS onset.",
  unsafe: "Pause at the tracing. This checkpoint grades the conduction pattern, not treatment. Complete the three evidence slots.",
  notAssessable: "The selected lead has readable P onsets and a grounded PR measurement. This pattern is assessable.",
  evidenceCue: "Prove 1:1, PR longer than 200 ms, and consistency.",
});

const s3Interactions: LearningInteraction[] = [
  {
    id: "m04-s3-p-march",
    kind: "march",
    prompt: "Show that every P wave conducts.",
    instructions: "Mark at least four P waves and verify a QRS follows each.",
    subskills: ["localize", "discriminate"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 1,
    target: "p_waves",
    minimumMarkers: 4,
    expectedPattern: "regular",
    toleranceMs: 60,
    feedback: s3Feedback,
    accessibility: accessibility({ instructions: "Mark every P wave.", keyboard: "Select P-wave event numbers in the timing table.", summary: "Four or more P waves, each followed by QRS." }),
  },
  {
    id: "m04-s3-pr",
    kind: "caliper",
    prompt: "Measure PR on three conducted beats.",
    instructions: "Confirm each value is longer than 200 ms and remains constant.",
    subskills: ["measure", "discriminate"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    measurement: "pr",
    target: { source: "packet_measurement", measurementKey: "pr_ms", toleranceMs: 30, lead: "II" },
    requireBoundaryLabels: true,
    feedback: s3Feedback,
    accessibility: accessibility({ instructions: "Measure three PR intervals.", keyboard: "Use P-onset and QRS-onset steppers for each beat.", summary: "Three long, constant PR intervals with one-to-one conduction." }),
  },
];

const s4Feedback = feedback({
  correct: "The conducted PR intervals lengthen, one P wave is not conducted, and the next cycle resets. That is Wenckebach.",
  partial: "You found the nonconducted P. Now prove the progressive PR change before it.",
  incorrect: "A pause is not the diagnosis. Bracket the repeating sequence and measure the conducted PR intervals.",
  unsafe: "Pause at the tracing. This checkpoint grades the Wenckebach sequence, not treatment. Complete the PR ladder.",
  notAssessable: "The teaching sequence exposes every P onset and QRS onset. The pattern is assessable here.",
  evidenceCue: "Start after the pause and follow progressive PR lengthening to the next nonconducted P.",
});

const s4Interactions: LearningInteraction[] = [
  compactInteraction({
    id: "m04-s4-av-ladder",
    kind: "model_explore",
    prompt: "Play one Wenckebach cycle in the AV ladder.",
    instructions: "Visit every impulse from reset through nonconduction and the next reset.",
    subskills: ["explain_mechanism"],
    model: "av_ladder",
    frames: [
      { id: "short", label: "Shorter conducted PR", narration: "The cycle begins after reset." },
      { id: "longer", label: "Longer conducted PR", narration: "AV conduction takes longer." },
      { id: "longest", label: "Longest conducted PR", narration: "Delay increases again." },
      { id: "blocked", label: "P not conducted", narration: "The atrial impulse has no ventricular response." },
      { id: "cycle-reset", label: "Cycle resets", narration: "The next conducted PR is shorter again." },
    ],
    requiredFrameIds: ["short", "longer", "longest", "blocked", "cycle-reset"],
    feedback: s4Feedback,
    accessibility: accessibility({ instructions: "Visit five numbered AV-ladder frames.", keyboard: "Use Previous impulse and Next impulse.", summary: "Progressive conducted delay, a blocked P, then reset." }),
  }),
  {
    id: "m04-s4-cycle-sequence",
    kind: "sequence",
    prompt: "Rebuild one full conduction cycle.",
    instructions: "Order the AV events from the reset through the nonconducted P wave.",
    subskills: ["explain_mechanism", "synthesize"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    cards: [
      { id: "conducts", label: "P conducts" },
      { id: "later", label: "Next P conducts later" },
      { id: "later-again", label: "Next P conducts later again" },
      { id: "drop", label: "P is not conducted" },
      { id: "reset", label: "The next conducted PR resets shorter" },
    ],
    correctOrder: ["conducts", "later", "later-again", "drop", "reset"],
    feedback: s4Feedback,
    accessibility: accessibility({ instructions: "Order five AV-cycle cards.", keyboard: "Use Move earlier and Move later controls.", summary: "Progressive conducted delay, a nonconducted P, then reset." }),
  },
  {
    id: "m04-s4-cycle-region",
    kind: "region",
    prompt: "Bracket one complete Wenckebach cycle on the rhythm strip.",
    instructions: "Span from the first shorter conducted PR through the nonconducted P.",
    subskills: ["localize", "discriminate"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    concept: "wenckebach_cycle",
    allowedLeads: ["II", "V1"],
    minimumDurationMs: 1200,
    feedback: s4Feedback,
    accessibility: accessibility({ instructions: "Select the first and last event of one full cycle.", keyboard: "Choose start and end event numbers in the timing table.", summary: "A complete cycle includes progressive PR change and the nonconducted P." }),
  },
];

const s5Feedback = feedback({
  correct: "Case A has fixed conducted PR intervals and an on-time nonconducted P, supporting Mobitz II. Case B’s hidden P is premature, supporting a blocked PAC mimic.",
  partial: "One evidence chain is supported. Finish the mimic by exposing and timing the P wave inside the T wave.",
  incorrect: "A dropped QRS after a premature P is not the same evidence as an on-time P that fails to conduct. Extend the atrial march.",
  unsafe: "Pause at the tracing. This checkpoint grades Mobitz II versus blocked PAC, not treatment. March the P waves.",
  notAssessable: "If reliable atrial timing is absent, keep ‘intermittent nonconduction; subtype not assessable.’ The eligible core case provides that timing.",
  evidenceCue: "Tag the nonconducted P as on time or premature relative to the atrial march.",
});

const s5Interactions: LearningInteraction[] = [
  {
    id: "m04-s5-p-march",
    kind: "march",
    prompt: "March the atrial events through the dropped QRS.",
    instructions: "Use at least six P markers across both contrast strips.",
    subskills: ["localize", "discriminate"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    target: "p_waves",
    minimumMarkers: 6,
    expectedPattern: "regular",
    toleranceMs: 70,
    feedback: s5Feedback,
    accessibility: accessibility({ instructions: "Mark atrial events across both strips.", keyboard: "Choose atrial events from synchronized timing rows.", summary: "One nonconducted P is on time; the blocked PAC is premature." }),
  },
  {
    id: "m04-s5-hidden-p",
    kind: "region",
    prompt: "Circle each nonconducted P and compare its timing.",
    instructions: "Use the T-wave teaching subtraction only for the authored blocked-PAC model.",
    subskills: ["localize", "discriminate"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    concept: "nonconducted_p_wave_timing",
    allowedLeads: ["II", "V1"],
    feedback: s5Feedback,
    accessibility: accessibility({ instructions: "Select the hidden or nonconducted P-wave region.", keyboard: "Choose the event and timing tag from the structured row.", summary: "The Mobitz-II P is on time; the blocked PAC is early." }),
  },
  {
    id: "m04-s5-contrast",
    kind: "compare",
    prompt: "Compare fixed conducted PR with premature hidden atrial activity.",
    instructions: "Complete timing and conducted-PR dimensions before assigning the patterns.",
    subskills: ["discriminate"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    leftCaseConcept: "mobitz_ii",
    rightCaseConcept: "blocked_pac",
    dimensions: [
      { id: "p-timing", label: "Nonconducted P timing", leftAnswer: "on time", rightAnswer: "premature" },
      { id: "pr", label: "Conducted PR", leftAnswer: "fixed", rightAnswer: "ectopic timing disrupts comparison" },
    ],
    feedback: s5Feedback,
    accessibility: accessibility({ instructions: "Complete a two-dimension timing comparison.", keyboard: "Use labeled fields for each case.", summary: "Mobitz II has on-time nonconduction; blocked PAC is premature." }),
  },
];

const s6Feedback = feedback({
  correct: "Exactly. The tracing supports second-degree AV block with 2:1 conduction. It does not show enough conducted PR intervals to prove Mobitz I or Mobitz II.",
  partial: "You demonstrated 2:1 conduction. Finish by stating that the Mobitz subtype is not determined here.",
  incorrect: "A single conducted PR between drops cannot demonstrate progressive behavior or prove fixed Mobitz-II behavior.",
  unsafe: "Pause at the tracing. This checkpoint grades the evidence limit, not treatment. Mark the 2:1 relationship.",
  notAssessable: "Partly right, but too vague. The subtype is not assessable; the 2:1 AV-block pattern is assessable.",
  evidenceCue: "Count two atrial events for each ventricular response, then stop at the supported claim.",
});

const s6Interactions: LearningInteraction[] = [
  {
    id: "m04-s6-p-march",
    kind: "march",
    prompt: "Reveal and mark every P wave in the 2:1 pattern.",
    instructions: "Link conducted P waves and leave blocked P waves unlinked.",
    subskills: ["localize", "discriminate"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    target: "p_waves",
    minimumMarkers: 8,
    expectedPattern: "regular",
    toleranceMs: 60,
    feedback: s6Feedback,
    accessibility: accessibility({ instructions: "Mark at least eight atrial events.", keyboard: "Use the atrial/ventricular relationship table.", summary: "Two atrial events occur for each QRS." }),
  },
  {
    id: "m04-s6-claim",
    kind: "free_response",
    prompt: "State the strongest interpretation this strip supports.",
    instructions: "Name the 2:1 pattern and explicitly limit the Mobitz subtype.",
    subskills: ["synthesize", "calibrate_confidence"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 1,
    responseLabel: "Evidence-limited interpretation",
    placeholder: "Second-degree AV block with …",
    minimumCharacters: 35,
    sentenceFrame: "Second-degree AV block with 2:1 conduction; …",
    rubric: [
      { id: "two-to-one", label: "Names 2:1 AV conduction", acceptedConcepts: ["2:1", "two to one", "every other P blocked"], required: true },
      { id: "uncertain-subtype", label: "Limits Mobitz subtype", acceptedConcepts: ["subtype uncertain", "not determined", "cannot distinguish Mobitz I from II", "not assessable"], required: true, misconceptionIfMissing: "forced_av_block_subtype" },
    ],
    feedback: s6Feedback,
    accessibility: accessibility({ instructions: "Write an evidence-limited AV-block statement.", keyboard: "Type or use speech input.", summary: "Required concepts are 2:1 conduction and an indeterminate Mobitz subtype." }),
  },
];

const s7Feedback = feedback({
  correct: "Atrial rate [atrial rate]/min and ventricular rate [ventricular rate]/min march independently; the apparent PR changes. That supports complete AV block with an escape rhythm.",
  partial: "Both rates may be correct. Show independence by marking changing apparent P–QRS relationships.",
  incorrect: "Sinus bradycardia and Mobitz II preserve a conducted relationship. Here P waves and QRS complexes move through one another.",
  unsafe: "Pause at the tracing. This checkpoint grades AV dissociation, not a pacing order. Complete both march rows.",
  notAssessable: "The strip is long enough and both event streams are visible. The AV relationship is assessable.",
  evidenceCue: "March P waves without QRS, then QRS without P; compare the phase over time.",
});

const s7Interactions: LearningInteraction[] = [
  {
    id: "m04-s7-atrial-march",
    kind: "march",
    prompt: "Set the atrial march across at least six seconds.",
    instructions: "Ignore QRS complexes while setting P–P spacing.",
    subskills: ["localize", "measure"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    target: "p_waves",
    minimumMarkers: 6,
    expectedPattern: "dissociated",
    toleranceMs: 60,
    feedback: s7Feedback,
    accessibility: accessibility({ instructions: "Mark the independent atrial row.", keyboard: "Select P events in the timing table.", summary: "A regular atrial clock independent of QRS." }),
  },
  {
    id: "m04-s7-ventricular-march",
    kind: "march",
    prompt: "Set the ventricular march without moving the atrial row.",
    instructions: "Mark at least five QRS complexes and inspect phase drift.",
    subskills: ["localize", "measure", "discriminate"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    target: "qrs_complexes",
    minimumMarkers: 5,
    expectedPattern: "dissociated",
    toleranceMs: 45,
    feedback: s7Feedback,
    accessibility: accessibility({ instructions: "Mark the independent ventricular row.", keyboard: "Select QRS events in the timing table.", summary: "A slower ventricular clock with phase drift relative to P waves." }),
  },
];

const s8Feedback = feedback({
  correct: "The beat arrives late after the expected rhythm fails. Its timing, rate, P relation, and QRS support the appropriately qualified escape description.",
  partial: "You described width and rate, but not timing. Mark where the expected beat failed before the escape appeared.",
  incorrect: "A PVC is premature. This beat arrives late, so start with ‘escape’ and qualify the likely focus.",
  unsafe: "Pause at the tracing. This checkpoint grades escape evidence, not device therapy. Mark the late beat and its QRS.",
  notAssessable: "If P waves are unclear, mark P relation ‘not assessable’; timing, rate, and QRS remain assessable.",
  evidenceCue: "Extend the expected rhythm through the pause and locate the late rescue beat.",
});

const s8Interactions: LearningInteraction[] = [
  {
    id: "m04-s8-escape-point",
    kind: "point",
    prompt: "Mark the late escape beat.",
    instructions: "Show the expected beat first, then select the rescue beat that follows the delay.",
    subskills: ["localize", "discriminate"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    concept: "escape_beat",
    gradePrompt: "Grade the selected late beat against the authored or packet escape event.",
    allowedLeads: ["II", "V1"],
    feedback: s8Feedback,
    accessibility: accessibility({ instructions: "Select the escape event after the expected-cycle marker.", keyboard: "Choose the event number in the timing table.", summary: "The escape beat is late rather than premature." }),
  },
  {
    id: "m04-s8-qrs",
    kind: "caliper",
    prompt: "Measure the escape QRS and qualify the focus.",
    instructions: "Use QRS width with rate and P relation; do not assign focus from width alone.",
    subskills: ["measure", "calibrate_confidence"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    measurement: "qrs",
    target: { source: "packet_measurement", measurementKey: "qrs_ms", toleranceMs: 30, lead: "II" },
    requireBoundaryLabels: true,
    feedback: s8Feedback,
    accessibility: accessibility({ instructions: "Measure QRS of the escape beat.", keyboard: "Use labeled QRS-onset and QRS-end steppers.", summary: "Width contributes to a junctional-appearing or ventricular-appearing qualified description." }),
  },
];

const s9Feedback = feedback({
  correct: "The rhythm is supported, the provided compromise cues determine priority, and reversible contributors remain hypotheses tested with clinical data.",
  partial: "Your rhythm evidence is supported. Finish the perfusion findings and reversible-cause check; do not infer them from the tracing.",
  incorrect: "A slow rate alone does not establish compromise or a cause. Use blood pressure, mental status, shock, chest discomfort, heart failure, history, oxygenation, labs, and prior ECG.",
  unsafe: "Exact treatment details depend on the patient, current protocol, and clinical team. This checkpoint grades the action category and evidence sources.",
  notAssessable: "Perfusion is not assessable from ECG alone; open the provided bedside assessment. The AV relationship itself is supported by the case packet.",
  evidenceCue: "Separate ECG facts, bedside compromise cues, and data needed to test reversible causes.",
});

const s9Interactions: LearningInteraction[] = [
  {
    id: "m04-s9-av-march",
    kind: "march",
    prompt: "Read the rhythm before revealing perfusion.",
    instructions: "March the atrial events and demonstrate their relationship to QRS.",
    subskills: ["discriminate", "synthesize"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    target: "p_waves",
    minimumMarkers: 6,
    expectedPattern: "dissociated",
    toleranceMs: 60,
    feedback: s9Feedback,
    accessibility: accessibility({ instructions: "Complete the AV relationship row.", keyboard: "Use the event table before opening clinical stages.", summary: "The tracing evidence is completed before bedside information is revealed." }),
  },
  {
    id: "m04-s9-clinical-stages",
    kind: "clinical_stage",
    prompt: "Reveal perfusion, choose the action category, then check reversible causes.",
    instructions: "Use only facts supplied by the authored scenario.",
    subskills: ["apply_in_context", "calibrate_confidence"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 1,
    stages: [
      {
        id: "perfusion",
        heading: "Bedside assessment",
        revealCopy: "Blood pressure is low and the patient is acutely confused. These are provided compromise cues, not ECG findings.",
        question: "Which priority category matches persistent bradycardia with cardiopulmonary compromise?",
        options: [
          { id: "escalate", label: "Immediate assessment, support, and escalation", rationale: "Correct action category." },
          { id: "observe", label: "Observe from the ECG station", rationale: "Does not address the provided compromise." },
          { id: "diagnose-cause", label: "Diagnose the cause from the ECG alone", rationale: "The tracing cannot establish the cause." },
        ],
        acceptableOptionIds: ["escalate"],
        unsafeOptionIds: ["observe", "diagnose-cause"],
      },
      {
        id: "reversible",
        heading: "Reversible-cause check",
        revealCopy: "Potential contributors include ischemia/infarction, drugs or toxicology, hypoxia, and electrolyte abnormalities such as hyperkalemia.",
        question: "Which next-data category keeps those causes as hypotheses rather than ECG certainties?",
        options: [
          { id: "obtain-data", label: "Review medications, oxygenation, electrolytes, ischemia context, and prior ECG", rationale: "Correct." },
          { id: "ecg-only", label: "Choose one cause from this tracing alone", rationale: "Unsupported causal certainty." },
        ],
        acceptableOptionIds: ["obtain-data"],
        unsafeOptionIds: ["ecg-only"],
      },
    ],
    feedback: s9Feedback,
    accessibility: accessibility({ instructions: "Complete two staged clinical decisions after the rhythm gate.", keyboard: "Use radio groups in each stage.", summary: "Bedside compromise determines priority; history, oxygenation, labs, and prior ECG test reversible causes." }),
  },
];

const s10Feedback = feedback({
  correct: "Your marks demonstrate the AV relationship, and your conclusion matches the strongest claim the tracing supports.",
  partial: "The conclusion is not released because a required waveform action is still unproven.",
  incorrect: "The label outruns the marks. Re-read the conducted PR behavior and the P–QRS relationship.",
  unsafe: "Pause at the tracing. This exit grades ECG interpretation and action category, not a treatment order.",
  notAssessable: "Use a limited statement only when the requested relationship is genuinely unavailable; at least one exit case intentionally requires that restraint.",
  evidenceCue: "Atrial rate and regularity → ventricular rate and regularity → P–QRS relationship → conducted PR behavior → QRS width.",
});

const s10Interactions: LearningInteraction[] = [
  {
    id: "m04-s10-relationship",
    kind: "march",
    prompt: "Run the six-step AV relationship on this unannounced case.",
    instructions: "Place atrial and ventricular evidence before writing the conclusion.",
    subskills: ["discriminate", "synthesize"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    target: "p_waves",
    minimumMarkers: 6,
    expectedPattern: "variable",
    toleranceMs: 60,
    feedback: s10Feedback,
    accessibility: accessibility({ instructions: "Mark the decisive atrial/ventricular relationship.", keyboard: "Use the structured six-step AV rail.", summary: "An independent AV relationship analysis on an unannounced case." }),
  },
  {
    id: "m04-s10-pr",
    kind: "caliper",
    prompt: "Measure conducted PR when a conducted relationship is present.",
    instructions: "Mark not assessable only when no stable conducted PR exists.",
    subskills: ["measure", "calibrate_confidence"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 2,
    measurement: "pr",
    target: { source: "packet_measurement", measurementKey: "pr_ms", toleranceMs: 30, lead: "II" },
    requireBoundaryLabels: true,
    feedback: s10Feedback,
    accessibility: accessibility({ instructions: "Measure or appropriately limit PR.", keyboard: "Use the beat table and Not assessable control.", summary: "PR evidence is measured only when a stable conducted interval exists." }),
  },
  {
    id: "m04-s10-synthesis",
    kind: "free_response",
    prompt: "Submit the strongest defensible conduction conclusion and confidence.",
    instructions: "Include the relationship evidence and any uncertainty.",
    subskills: ["synthesize", "calibrate_confidence"],
    requiredForCompletion: true,
    maxAttemptsBeforeScaffold: 1,
    responseLabel: "Conduction conclusion",
    placeholder: "Atrial and ventricular relationship …",
    minimumCharacters: 45,
    rubric: [
      { id: "relationship", label: "Names P–QRS relationship", acceptedConcepts: ["1:1", "progressive PR", "fixed PR", "2:1", "AV dissociation", "blocked PAC"], required: true, misconceptionIfMissing: "av_relationship_missing" },
      { id: "evidence-limit", label: "Matches claim strength", acceptedConcepts: ["supported", "not determined", "not assessable", "uncertain subtype", "complete AV block", "first-degree", "Mobitz"], required: true, misconceptionIfMissing: "av_claim_overreach" },
    ],
    feedback: s10Feedback,
    accessibility: accessibility({ instructions: "Write a concise evidence-first conclusion.", keyboard: "Type or use speech input.", summary: "A complete AV relationship conclusion with calibrated uncertainty." }),
  },
];

export const M04_AV_CONDUCTION_MODULE: ProductionModule = {
  id: "av-brady",
  order: 4,
  title: "AV Conduction and Bradyarrhythmias",
  shortTitle: "AV conduction",
  duration: "50–65 min",
  outcome: "Measure PR, prove AV relationships, distinguish supported block patterns, preserve 2:1 uncertainty, recognize escape rhythms, and connect bradycardia to perfusion without inferring bedside facts from the ECG.",
  prerequisiteIds: ["rhythm-ectopy"],
  accent: "#4777C8",
  sourceRequirementIds: ["SPEC-11.5", "SPEC-11.13", "SPEC-7.av_block_*", "SPEC-16.av_block_confusion", "AHA25-BRADY"],
  scenes: [
    buildScene({
      id: "m04-s0", partId: "m04-part-1", minutes: 5,
      source: sources("M4-S0", ["SPEC-11.13", "SPEC-16.av_block_confusion", "M3-RHYTHM"]),
      copy: sceneCopy({ eyebrow: "M4 · 1 of 11", title: "Two clocks, one relationship", objective: "Before naming a block, prove what the atria and ventricles are doing.", openingTutorMessage: "Do not name either rhythm yet. Mark the atrial clock first, then the ventricular clock.", setup: ["A slow ventricular rate does not tell you where an impulse was delayed or lost."], mechanismNarration: ["Start with two clocks: mark every atrial event, mark every ventricular event, then ask how the clocks relate."], clinicalConnectionHeading: "Evidence before label", clinicalConnectionBody: "Early ectopy and an on-time nonconducted impulse can both create a pause; their atrial timing differs.", transitionIntoTask: focus, completionBody: "Timing evidence now separates an early atrial beat from an on-time P wave without QRS." }),
      layout: responsiveLayout("Two synchronized strips use a shared ruler; mobile preserves marks between Strip A and Strip B tabs."),
      tutor: tutorContract({ socratic: "On Strip A, is the unusual atrial event early, on time, or late compared with the sinus march?", hints: ["Ignore the QRS for one pass. March only the P waves.", "An early atrial event suggests ectopy. A sinus P that arrives on schedule but has no QRS raises a conduction question."], tangentBridge: "Let’s take that tangent. I’ll keep your exact place in this scene.", returnPrompt: "Back to the two clocks: finish the P markers before judging the missing QRS." }),
      caseContract: caseSpec({ selectorLessonId: "pr-av-block", requestedConcept: "av_block_second_degree_mobitz_ii", minimumTier: "A", requiredEvidence: ["P-wave centers", "QRS onsets", "expected sinus cycle", "conducted status"], requiredLeads: ["II", "V1"], allowedUses: ["mechanism", "worked_example", "scored_recognition"], fallback: "authored_simulation", forbiddenClaims: ["Specific block label before timing evidence", "Treatment recommendation"] }),
      interactions: s0Interactions, minimumScore: 0.9,
      connections: { recallFrom: "M3 premature atrial beats and pauses", changesNow: "Atrial and ventricular clocks are analyzed independently", reuseNext: "Every later AV-block scene", clinicalUse: "Avoid calling a pause a block from ventricular timing alone" },
      handoffs: [handoff("train", "Train · P–QRS relationship", "av_relationship", "discriminate", "guided")],
    }),
    buildScene({
      id: "m04-s1", partId: "m04-part-1", minutes: 5,
      source: sources("M4-S1", ["SPEC-11.5", "FOUND-S6", "ARCH-M4"]),
      copy: sceneCopy({ eyebrow: "M4 · 2 of 11", title: "The relay and the fast network", objective: "Separate AV delay from ventricular spread.", openingTutorMessage: "Change one pathway at a time. Predict the interval before you move the control.", setup: ["The AV node normally delays the impulse before it enters the His–Purkinje network."], mechanismNarration: ["The PR interval reflects the atrial-to-ventricular journey; the QRS reflects ventricular activation.", "A long PR and a wide QRS answer different questions."], clinicalConnectionHeading: "Do not localize from one number", clinicalConnectionBody: "Surface intervals describe timing; they do not always pinpoint the anatomical level of disease.", transitionIntoTask: "Predict what changes, then adjust one pathway only.", completionBody: "You isolated AV delay from ventricular-spread delay." }),
      layout: responsiveLayout("The conduction tree and live lead-II beat remain synchronized; mobile stacks numbered frames above numeric readouts."),
      tutor: tutorContract({ socratic: "If the ventricles still activate quickly after a longer wait, which measurement changes?", hints: ["PR ends where QRS begins.", "Changing the relay delay moves QRS onset later. Changing ventricular spread stretches the QRS itself."], tangentBridge: "Let’s take that tangent. I’ll preserve both model settings.", returnPrompt: "Return to the model: reset it, then change only ventricular spread." }),
      caseContract: caseSpec({ selectorLessonId: "pr-av-block", requestedConcept: "pr_interval", minimumTier: "A", requiredEvidence: ["Authored P onset", "Authored QRS onset and end", "Exact PR and QRS duration"], requiredLeads: ["II"], allowedUses: ["mechanism", "measurement"], fallback: "authored_simulation", forbiddenClaims: ["Precise anatomical localization from surface interval", "Treatment"] }),
      interactions: s1Interactions, minimumScore: 0.9,
      connections: { recallFrom: "Foundations PR and QRS boundaries", changesNow: "The two intervals are linked to separate mechanisms", reuseNext: "Long PR and wide-QRS pattern recognition", clinicalUse: "Prevents treating PR prolongation as ventricular delay" },
      handoffs: [handoff("train", "Train · PR versus QRS boundaries", "pr_qrs_boundaries", "measure", "guided")],
    }),
    buildScene({
      id: "m04-s2", partId: "m04-part-1", minutes: 6,
      source: sources("M4-S2", ["SPEC-11.5", "SPEC-8.4", "ARCH-M4"]),
      copy: sceneCopy({ eyebrow: "M4 · 3 of 11", title: "Measure the relationship across beats", objective: "Decide whether conducted PR intervals are constant, progressive, or variable.", openingTutorMessage: "Measure first. The labels stay hidden until the PR row is complete.", setup: ["One PR interval is a snapshot. AV-conduction patterns live across beats."], mechanismNarration: ["Use the same lead, mark the same boundaries, and compare every conducted beat before naming the pattern."], clinicalConnectionHeading: "Patterns require time", clinicalConnectionBody: "A single beat cannot demonstrate progressive delay or AV dissociation.", transitionIntoTask: "Measure each conducted PR, then name the beat-to-beat pattern.", completionBody: "The measured PR row now distinguishes constant, progressive, and unstable relationships." }),
      layout: responsiveLayout("A synchronized PR row sits beneath the strip; mobile uses a beat stack with the current beat pinned."),
      tutor: tutorContract({ socratic: "Do the measured PR values move in one direction, remain within measurement noise, or fail to form a stable relationship?", hints: ["Use the same P and QRS boundaries on every beat.", "A variable apparent PR is not the same as progressive lengthening."], tangentBridge: "Let’s pause the measurement row without changing it.", returnPrompt: "Back to beat [n]: place P onset, then QRS onset." }),
      caseContract: caseSpec({ selectorLessonId: "pr-av-block", requestedConcept: "av_block_first_degree", minimumTier: "A", requiredEvidence: ["PR measurement or fiducials", "Beat-level P/QRS onsets", "Conducted status"], requiredLeads: ["II", "V1"], allowedUses: ["measurement", "worked_example", "scored_recognition"], fallback: "authored_simulation", forbiddenClaims: ["Pattern classification from one PR interval"] }),
      interactions: s2Interactions,
      connections: { recallFrom: "M4-S1 interval mechanisms", changesNow: "PR becomes a sequence rather than one value", reuseNext: "First-degree, Wenckebach, Mobitz II, and complete block", clinicalUse: "Prevents subtype claims from a single beat" },
      handoffs: [handoff("train", "Train · PR sequence", "pr_sequence", "measure", "guided")],
    }),
    buildScene({
      id: "m04-s3", partId: "m04-part-2", minutes: 5,
      source: sources("M4-S3", ["SPEC-11.13", "SPEC-7.av_block_first_degree", "SPEC-8.4"]),
      copy: sceneCopy({ eyebrow: "M4 · 4 of 11", title: "Every P conducts, but slowly", objective: "Prove a first-degree AV-block pattern from three findings.", openingTutorMessage: "Build the label from evidence. First show that every P gets through.", setup: ["First-degree AV block is a conduction pattern: every P wave conducts, the PR interval is longer than 200 ms, and the conducted PR stays constant."], mechanismNarration: ["Nothing is dropped."], clinicalConnectionHeading: "Pattern is not a patient plan", clinicalConnectionBody: "Symptoms, medications, prior ECGs, and the broader setting determine the clinical meaning.", transitionIntoTask: "Fill all three evidence slots for this long-PR pattern.", completionBody: "One-to-one conduction, long PR, and constant PR now support the label." }),
      layout: responsiveLayout("The full lead-II strip sits above evidence slots labeled 1:1, PR >200 ms, and PR constant."),
      tutor: tutorContract({ socratic: "What distinguishes a long but fully conducted PR from a second-degree block?", hints: ["Count P waves and QRS complexes before measuring.", "Longer than 200 ms means more than five small boxes at standard speed."], tangentBridge: "I’ll keep the links and calipers exactly where they are.", returnPrompt: "Back to the evidence tray: fill the 1:1 slot first." }),
      caseContract: caseSpec({ selectorLessonId: "pr-av-block", requestedConcept: "av_block_first_degree", minimumTier: "A", requiredEvidence: ["PR >200 ms", "Compatible label or statement", "Readable P waves", "One-to-one conduction"], requiredLeads: ["II"], allowedUses: ["measurement", "scored_recognition"], fallback: "authored_simulation", forbiddenClaims: ["Second-degree AV block without dropped conduction", "Treatment"] }),
      interactions: s3Interactions, minimumScore: 0.9,
      connections: { recallFrom: "M4-S2 constant PR behavior", changesNow: "A named pattern is earned from three findings", reuseNext: "Contrast with every dropped-conduction pattern", clinicalUse: "Separates a long conducted interval from dropped beats" },
      handoffs: [handoff("train", "Train · Long PR versus dropped conduction", "av_block_first_degree", "discriminate", "faded")],
    }),
    buildScene({
      id: "m04-s4", partId: "m04-part-2", minutes: 6,
      source: sources("M4-S4", ["SPEC-11.13", "SPEC-7.av_block_second_degree_mobitz_i", "SPEC-8.4"]),
      copy: sceneCopy({ eyebrow: "M4 · 5 of 11", title: "Grouped beating: Wenckebach", objective: "See the cycle, not a single pause.", openingTutorMessage: "Play one cycle, then rebuild it yourself. Watch the PR interval, not just the pause.", setup: ["In Mobitz I, or Wenckebach, conducted PR intervals progressively lengthen until a P wave is not followed by QRS; then the cycle resets."], mechanismNarration: ["Grouped beating is the consequence of that repeating sequence."], clinicalConnectionHeading: "Cycle evidence", clinicalConnectionBody: "If P onsets are obscured, the Mobitz subtype should remain unclaimed.", transitionIntoTask: "Rebuild one full conduction cycle, then bracket it on the strip.", completionBody: "The repeating progressive-delay, drop, and reset sequence is demonstrated." }),
      layout: responsiveLayout("The ladder diagram and rhythm strip share vertical event lines; mobile advances one impulse at a time."),
      tutor: tutorContract({ socratic: "After the dropped QRS, what happens to the next conducted PR?", hints: ["Start at the P wave immediately after the pause.", "The evidence is progressive change before the drop, followed by reset."], tangentBridge: "I’ll freeze this cycle at the current impulse.", returnPrompt: "Back to the cycle: bracket from the first short PR through the nonconducted P." }),
      caseContract: caseSpec({ selectorLessonId: "pr-av-block", requestedConcept: "av_block_second_degree_mobitz_i", minimumTier: "A", requiredEvidence: ["Explicit Mobitz-I support or authored model", "Readable P onsets", "Progressive PR sequence", "Dropped QRS", "Cycle reset"], requiredLeads: ["II", "V1"], allowedUses: ["mechanism", "scored_recognition"], fallback: "authored_simulation", forbiddenClaims: ["Real-case Mobitz-I competency without eligible evidence"] }),
      interactions: s4Interactions,
      connections: { recallFrom: "M4-S2 progressive PR row", changesNow: "The row becomes a repeating conduction cycle", reuseNext: "Direct contrast with Mobitz II", clinicalUse: "Avoids diagnosing from the pause alone" },
      handoffs: [handoff("train", "Train · Wenckebach cycles", "av_block_second_degree_mobitz_i", "discriminate", "faded")],
    }),
    buildScene({
      id: "m04-s5", partId: "m04-part-2", minutes: 7,
      source: sources("M4-S5", ["SPEC-11.13", "SPEC-7.av_block_second_degree_mobitz_ii", "SPEC-16.av_block_confusion"]),
      copy: sceneCopy({ eyebrow: "M4 · 6 of 11", title: "A dropped QRS without progressive delay", objective: "Distinguish a fixed conducted PR from a hidden premature atrial beat.", openingTutorMessage: "Both strips contain a P without QRS. The atrial timing decides whether they tell the same story.", setup: ["In Mobitz II, conducted beats keep a fixed PR interval and an on-time P wave unexpectedly fails to conduct."], mechanismNarration: ["Rule out a premature hidden P wave, artifact, and an indeterminate 2:1 pattern before using the label."], clinicalConnectionHeading: "Mimic check", clinicalConnectionBody: "A blocked PAC can deform the T wave and imitate dropped conduction.", transitionIntoTask: "March the atrial events and tag each nonconducted P as on time or premature.", completionBody: "Fixed conducted PR plus an on-time nonconducted P is separated from a premature blocked PAC." }),
      layout: responsiveLayout("Two synchronized cases share a ruler; the teaching T-wave subtraction is available only on the authored blocked-PAC model."),
      tutor: tutorContract({ socratic: "Does the nonconducted P land on the expected atrial march, or arrive early and deform the T wave?", hints: ["Extend the P–P march through the pause.", "Fixed PR plus an on-time nonconducted P supports Mobitz II; an early P supports a blocked PAC."], tangentBridge: "I’ll preserve the shared ruler and both case marks.", returnPrompt: "Back to the circled P: tag its timing relative to the atrial march." }),
      caseContract: caseSpec({ selectorLessonId: "pr-av-block", requestedConcept: "av_block_second_degree_mobitz_ii", minimumTier: "A", requiredEvidence: ["Explicit Mobitz-II support", "Stable conducted PR", "On-time nonconducted P", "Blocked-PAC contrast"], requiredLeads: ["II", "V1"], allowedUses: ["scored_recognition", "transfer"], fallback: "authored_simulation", forbiddenClaims: ["Mobitz II from QRS width", "Mobitz II when atrial timing is unavailable"] }),
      interactions: s5Interactions, minimumScore: 0.9,
      connections: { recallFrom: "M3 blocked PAC and M4-S4 Wenckebach", changesNow: "Timing discriminates a high-stakes mimic", reuseNext: "2:1 uncertainty and mixed AV-block transfer", clinicalUse: "Prevents hidden ectopy from becoming a false conduction diagnosis" },
      handoffs: [handoff("train", "Train · On-time versus premature nonconducted P", "mobitz_ii_vs_blocked_pac", "discriminate", "faded")],
    }),
    buildScene({
      id: "m04-s6", partId: "m04-part-2", minutes: 5,
      source: sources("M4-S6", ["SPEC-11.13", "SPEC-16.av_block_confusion", "ACC18-CONDUCTION"]),
      copy: sceneCopy({ eyebrow: "M4 · 7 of 11", title: "2:1 conduction: stop at the evidence", objective: "Use calibrated uncertainty when every other P is blocked.", openingTutorMessage: "This scene rewards restraint. Show the ratio, then stop where the tracing stops.", setup: ["With every other P wave blocked, only one conducted PR appears before each drop."], mechanismNarration: ["Progressive versus fixed behavior may be impossible to establish; the defensible statement is second-degree AV block with 2:1 conduction, Mobitz subtype uncertain."], clinicalConnectionHeading: "Uncertainty is a skill", clinicalConnectionBody: "A more specific label is not better when the tracing cannot demonstrate it.", transitionIntoTask: "Show the 2:1 relationship, then stop at the strongest supported statement.", completionBody: "You named the visible 2:1 block and correctly limited the subtype." }),
      layout: responsiveLayout("A claim-strength ladder sits beneath a strip with progressively revealed atrial events."),
      tutor: tutorContract({ socratic: "How many conducted PR intervals are visible before each blocked P—and can they demonstrate progression?", hints: ["Count atrial and ventricular events separately.", "Two atrial events for each QRS establishes 2:1 conduction, not an automatic Mobitz subtype."], tangentBridge: "I’ll keep the revealed atrial events and links intact.", returnPrompt: "Back to the claim ladder: place the strongest statement the tracing actually proves." }),
      caseContract: caseSpec({ selectorLessonId: "pr-av-block", requestedConcept: "second_degree_av_block_2_to_1", minimumTier: "A", requiredEvidence: ["Regular atrial events", "2:1 P-to-QRS relationship", "Subtype explicitly indeterminate"], requiredLeads: ["II", "V1"], allowedUses: ["mechanism", "scored_recognition"], fallback: "authored_simulation", forbiddenClaims: ["Forced Mobitz-I subtype", "Forced Mobitz-II subtype"] }),
      interactions: s6Interactions, minimumScore: 0.9,
      connections: { recallFrom: "M4-S4 and M4-S5 subtype evidence", changesNow: "The learner must stop before unsupported specificity", reuseNext: "Every later claim-strength task", clinicalUse: "Communicates a high-grade pattern without false certainty" },
      handoffs: [handoff("train", "Train · 2:1 claim strength", "av_block_2_to_1", "calibrate_confidence", "faded")],
    }),
    buildScene({
      id: "m04-s7", partId: "m04-part-3", minutes: 6,
      source: sources("M4-S7", ["SPEC-11.13", "SPEC-7.av_block_third_degree", "ACC18-CONDUCTION"]),
      copy: sceneCopy({ eyebrow: "M4 · 8 of 11", title: "Two clocks uncoupled", objective: "Demonstrate AV dissociation across several beats.", openingTutorMessage: "March P waves without looking at QRS. Then march QRS complexes without looking at P.", setup: ["In complete AV block, atrial impulses do not conduct to the ventricles."], mechanismNarration: ["P waves keep their own rhythm; an escape rhythm keeps the ventricles going. Apparent PR changes because the clocks are independent."], clinicalConnectionHeading: "Dissociation requires duration", clinicalConnectionBody: "Several beats are needed to prove that P waves and QRS complexes slide through one another.", transitionIntoTask: "March atria and ventricles separately, then test whether the clocks stay linked.", completionBody: "Independent atrial and ventricular clocks now demonstrate AV dissociation." }),
      layout: responsiveLayout("Atrial and ventricular timing rows project onto a minimum ten-second strip."),
      tutor: tutorContract({ socratic: "If the clocks are independent, what should happen to the apparent PR interval over time?", hints: ["Find two clear P waves and extend their spacing through the strip.", "A true conducted relationship preserves timing; here P waves slide through QRS."], tangentBridge: "I’ll freeze both marches and the current zoom.", returnPrompt: "Back to the two marches: finish the ventricular row before comparing them." }),
      caseContract: caseSpec({ selectorLessonId: "pr-av-block", requestedConcept: "av_block_third_degree", minimumTier: "A", requiredEvidence: ["Explicit complete-block support", "Atrial and ventricular events", "No stable conducted relationship", "Escape rate"], requiredLeads: ["II", "V1"], allowedUses: ["scored_recognition", "transfer"], fallback: "authored_simulation", forbiddenClaims: ["Sinus bradycardia from ventricular rate", "Precise escape focus without evidence"] }),
      interactions: s7Interactions, minimumScore: 0.9,
      connections: { recallFrom: "M4-S0 two-clock method", changesNow: "Both clocks persist without phase lock", reuseNext: "Escape rhythm and bradycardia context", clinicalUse: "Recognizes a high-grade conduction pattern from direct timing evidence" },
      handoffs: [handoff("train", "Train · AV dissociation", "av_block_third_degree", "discriminate", "faded"), handoff("clinical", "Clinical preview · severe bradycardia", "bradycardia_with_pulse", "apply_in_context", "guided", { focus: "bradycardia", subskill: "apply_in_context", lane: "ed", length: 5 })],
    }),
    buildScene({
      id: "m04-s8", partId: "m04-part-3", minutes: 5,
      source: sources("M4-S8", ["SPEC-11.13", "M3-RHYTHM", "ARCH-M4"]),
      copy: sceneCopy({ eyebrow: "M4 · 9 of 11", title: "Who rescues the ventricles?", objective: "Describe an escape rhythm without pretending one feature proves its origin.", openingTutorMessage: "First prove the beat is late. Only then ask where the rescue impulse may have started.", setup: ["An escape beat is late, not premature: it appears because a faster pacemaker did not produce a conducted beat in time."], mechanismNarration: ["Junctional escape is often narrower and faster than ventricular escape, but width and rate have exceptions."], clinicalConnectionHeading: "Qualified focus", clinicalConnectionBody: "Describe timing, P relation, rate, and QRS before assigning confidence to the focus.", transitionIntoTask: "Prove the beat is late before you describe the escape focus.", completionBody: "Timing now anchors a qualified escape description." }),
      layout: responsiveLayout("A conduction-tree focus model sits beside the strip; mobile uses selectable focus nodes."),
      tutor: tutorContract({ socratic: "What timing feature separates an escape beat from a premature beat?", hints: ["Extend the expected rhythm through the pause.", "Use junctional-appearing or ventricular-appearing when the surface evidence is suggestive rather than definitive."], tangentBridge: "I’ll preserve the expected-cycle guide and selected beat.", returnPrompt: "Back to the evidence slots: timing comes before focus." }),
      caseContract: caseSpec({ selectorLessonId: "pr-av-block", requestedConcept: "escape_rhythm", minimumTier: "B", requiredEvidence: ["Expected-cycle timing", "Escape beat time", "Rate", "QRS duration", "P relation"], requiredLeads: ["II", "V1"], allowedUses: ["mechanism", "measurement", "scored_recognition"], fallback: "authored_simulation", forbiddenClaims: ["PVC label for a late beat", "Certain anatomical focus from width alone"] }),
      interactions: s8Interactions,
      connections: { recallFrom: "M3 early versus late beats", changesNow: "A late rescue beat is separated from ectopy", reuseNext: "Complete-block escape and bradycardia cases", clinicalUse: "Avoids treating all wide isolated beats as premature" },
      handoffs: [handoff("train", "Train · Escape timing", "escape_rhythm", "discriminate", "guided")],
    }),
    buildScene({
      id: "m04-s9", partId: "m04-part-4", minutes: 7,
      source: sources("M4-S9", ["SPEC-11.13", "SPEC-7.bradycardia", "AHA25-BRADY"]),
      copy: sceneCopy({ eyebrow: "M4 · 10 of 11", title: "Bradycardia: the tracing and the perfusion check", objective: "Separate rhythm classification from cardiopulmonary compromise.", openingTutorMessage: "Read the tracing first. I will not reveal blood pressure or symptoms until the AV relationship is supported.", setup: ["Bradycardia is an ECG rate finding. Urgency comes from the person’s perfusion and clinical context."], mechanismNarration: ["Potential reversible contributors include ischemia or infarction, drugs or toxicology, hypoxia, and electrolyte abnormalities such as hyperkalemia.", "The ECG raises hypotheses; medication history, oxygenation, labs, prior tracing, and clinical story test them."], clinicalConnectionHeading: "Scenario-based learning only", clinicalConnectionBody: "Follow current local protocols in clinical care.", transitionIntoTask: "Read the rhythm, reveal perfusion, choose the action category, then check reversible causes.", completionBody: "You kept rhythm evidence, perfusion, and cause-finding data in their proper lanes." }),
      layout: responsiveLayout("Four locked stages reveal ECG, perfusion, action category, and reversible-cause data in order."),
      tutor: tutorContract({ socratic: "Which facts come from the ECG, and which require bedside assessment?", hints: ["The ECG can show rate and conduction; it cannot show blood pressure or mental status.", "Compromise changes the action category. A slow rate alone does not supply that context."], tangentBridge: "I’ll keep the current stage and all marks frozen.", returnPrompt: "Back to Stage [stage]: complete the tracing evidence before the next clinical reveal." }),
      caseContract: caseSpec({ selectorLessonId: "pr-av-block", requestedConcept: "av_block_third_degree", minimumTier: "A", requiredEvidence: ["Grounded rhythm and rate", "Authored pulse and perfusion facts", "Authored reversible-cause data categories"], requiredLeads: ["II", "V1"], allowedUses: ["transfer"], fallback: "authored_simulation", forbiddenClaims: ["Perfusion inferred from ECG", "Cause diagnosed from ECG alone", "Drug dose", "Device setting"] }),
      interactions: s9Interactions, minimumScore: 0.9,
      connections: { recallFrom: "M4-S7 AV dissociation", changesNow: "Bedside perfusion and reversible causes are added without contaminating ECG truth", reuseNext: "Clinical bradycardia with a pulse", clinicalUse: "Perfusion-first escalation and cause investigation" },
      handoffs: [handoff("clinical", "Clinical · Bradycardia with a pulse", "bradycardia_with_pulse", "apply_in_context", "faded", { focus: "bradycardia", subskill: "apply_in_context", lane: "clinic", length: 5 }), handoff("train", "Train · Bradycardia context", "brady_context", "calibrate_confidence", "guided")],
    }),
    buildScene({
      id: "m04-s10", partId: "m04-part-4", minutes: 8,
      source: sources("M4-S10", ["SPEC-11.13", "SPEC-12.1", "ARCH-M4"]),
      copy: sceneCopy({ eyebrow: "M4 · 11 of 11", title: "Conduction handoff", objective: "Interpret unannounced patterns and state the evidence limit.", openingTutorMessage: "I’ll stay quiet while you work. Ask if you want coaching; asking pauses the case and records the assistance level.", setup: ["Run the same sequence every time: atrial rate and regularity → ventricular rate and regularity → P–QRS relationship → conducted PR behavior → QRS width → strongest defensible conclusion."], mechanismNarration: ["One case deliberately requires subtype uncertainty."], clinicalConnectionHeading: "Independent evidence", clinicalConnectionBody: "Tutorial completion is separated from independent pattern mastery and confidence calibration.", transitionIntoTask: "Run the six-step AV relationship on this unannounced case.", completionHeading: "Module complete", completionBody: "You can prove an AV relationship, distinguish progressive, fixed, absent, and indeterminate conduction, and connect bradycardia to perfusion without guessing from rate alone." }),
      layout: responsiveLayout("A persistent six-step rail sits beside the ECG; Luna is collapsed by default."),
      tutor: tutorContract({ socratic: "Which step in the relationship sequence has not been demonstrated yet?", hints: ["March P waves and QRS complexes separately.", "Use the conducted PR pattern to distinguish progressive, fixed, absent, or indeterminate relationships."], tangentBridge: "Your marks, viewport, timer, and draft are frozen.", returnPrompt: "Back to case [n], with your marks and draft intact." }),
      caseContract: caseSpec({ selectorLessonId: "pr-av-block", requestedConcept: "av_conduction_mixed", minimumTier: "A", requiredEvidence: ["Contract-matched first degree, Mobitz contrast, 2:1 uncertainty, complete block, or blocked PAC", "P/QRS events", "PR behavior", "QRS duration"], requiredLeads: ["II", "V1"], allowedUses: ["scored_recognition", "measurement", "transfer"], fallback: "authored_simulation", forbiddenClaims: ["Unsupported subtype", "Treatment order"] }),
      interactions: s10Interactions, minimumScore: 0.8,
      connections: { recallFrom: "All M4 relationship patterns", changesNow: "Targets are unannounced and assistance is metered", reuseNext: "M5 ventricular activation and Clinical/Rapid practice", clinicalUse: "A concise, defensible conduction interpretation" },
      handoffs: [handoff("train", "Train · AV conduction contrasts", "av_conduction_mixed", "discriminate", "independent"), handoff("rapid", "Rapid · Bradycardia recognition", "bradycardia", "synthesize", "independent", { focus: "bradycardia", receiptConcept: "bradycardia", subskill: "recognize", pace: "untimed", suggestedLength: 5 }), handoff("clinical", "Clinical · Bradycardia with a pulse", "bradycardia_with_pulse", "apply_in_context", "faded", { focus: "bradycardia", subskill: "apply_in_context", lane: "clinic", length: 5 })],
    }),
  ],
};

export default M04_AV_CONDUCTION_MODULE;
