import type { FeedbackBranch, LearningInteraction, ProductionModule } from "@/lib/learning/interactionTypes";
import {
  accessibility,
  buildScene,
  caseSpec,
  compactInteraction,
  feedback,
  handoff,
  responsiveLayout,
  sceneCopy,
  sources,
  tutorContract,
} from "@/lib/learning/modules/m04M06ModuleHelpers";

const ax = (summary: string) => accessibility({
  instructions: summary,
  keyboard: "Use the synchronized lead table, event/region selectors, and arrow-key measurement steppers; drag is never required.",
  summary,
});

const fb = (correct: string, partial: string, incorrect: string, unsafe: string, notAssessable: string, evidenceCue: string): FeedbackBranch[] =>
  feedback({ correct, partial, incorrect, unsafe, notAssessable, evidenceCue });

const s0fb = fb(
  "The measured QRS duration answers how long activation took. The authored terminal-force model then shows why width alone cannot name the pathway.",
  "Your duration is correct. Now use the model to predict paired V1/V6 terminal polarity; ‘wide’ is not a bundle diagnosis.",
  "Equal duration does not make equal morphology. Compare the final force in V1 with the lateral terminal force.",
  "Pause at the tracing. This checkpoint grades activation evidence, not treatment. Complete duration and terminal morphology.",
  "The required leads and QRS boundaries are available. Width and broad morphology are assessable.",
  "Use QRS onset to final return to baseline, then isolate the terminal—not merely tallest—force.",
);
const s0i: LearningInteraction[] = [
  compactInteraction({ id: "m05-s0-qrs", kind: "caliper", prompt: "Measure QRS duration on the active tracing.", instructions: "Place the boundaries at QRS onset and the final return to baseline in V1.", subskills: ["measure"], measurement: "qrs", target: { source: "packet_measurement", measurementKey: "qrs_ms", toleranceMs: 25, lead: "V1" }, requireBoundaryLabels: true, feedback: s0fb, accessibility: ax("A labeled QRS-duration measurement in V1 on the active tracing.") }),
  compactInteraction({ id: "m05-s0-terminal", kind: "vector_lab", prompt: "Use the authored late-rightward model to predict paired terminal polarity.", instructions: "Rotate the teaching vector, then commit the expected terminal sign in V1 and V6. This model does not localize morphology on the active patient tracing.", subskills: ["explain_mechanism"], initialAngleDeg: 0, targetAngleDeg: 90, toleranceDeg: 30, targetLabel: "authored late-rightward teaching sector", predictions: [{ lead: "V1", expected: "positive" }, { lead: "V6", expected: "negative" }], feedback: s0fb, accessibility: ax("An authored terminal-force model predicting positivity in V1 and negativity in V6; it is separate from patient-trace localization.") }),
];

const s1fb = fb(
  "The final force points toward the ventricle activated last: rightward/toward V1 with right-bundle delay and leftward/toward lateral leads with left-bundle delay.",
  "You identified the delayed side, but your arrow shows the early force. Scrub to the final third of QRS.",
  "The final force points toward tissue activated last, not the side activated first.",
  "Pause at the model. This checkpoint grades activation mechanics, not treatment. Predict the final force.",
  "The deterministic model exposes the full activation sequence. Terminal direction is assessable.",
  "V1 looks from the right/anterior chest; V6 looks from the left/lateral chest.",
);
const s1i: LearningInteraction[] = [
  compactInteraction({ id: "m05-s1-model", kind: "model_explore", prompt: "Block each bundle and follow the activation sequence frame by frame.", instructions: "Visit normal activation, right-bundle delay, and left-bundle delay before drawing terminal vectors.", subskills: ["explain_mechanism"], model: "bundle_activation", frames: [{ id: "normal", label: "Both bundles conduct", narration: "The ventricles activate rapidly together.", activeRegion: "his_purkinje" }, { id: "right-delay", label: "Right bundle delayed", narration: "The left ventricle activates first; the late force turns rightward.", activeRegion: "ventricles" }, { id: "left-delay", label: "Left bundle delayed", narration: "The right ventricle activates first; the late force turns leftward.", activeRegion: "ventricles" }], requiredFrameIds: ["normal", "right-delay", "left-delay"], feedback: s1fb, accessibility: ax("Three static bundle-activation frames: normal, right delay, and left delay.") }),
  compactInteraction({ id: "m05-s1-right-vector", kind: "vector_lab", prompt: "Delay the right bundle and predict the terminal force before scrubbing.", instructions: "Draw the late rightward force and predict terminal positivity in V1.", subskills: ["explain_mechanism"], initialAngleDeg: -30, targetAngleDeg: 90, toleranceDeg: 30, targetLabel: "late rightward force toward V1", predictions: [{ lead: "V1", expected: "positive" }, { lead: "V6", expected: "negative" }], feedback: s1fb, accessibility: ax("A right-bundle-delay model with a terminal force toward V1 and away from V6.") }),
  compactInteraction({ id: "m05-s1-left-vector", kind: "vector_lab", prompt: "Reset, delay the left bundle, and predict the terminal force.", instructions: "Draw the late leftward force and predict terminal negativity in V1.", subskills: ["explain_mechanism"], initialAngleDeg: 60, targetAngleDeg: 180, toleranceDeg: 30, targetLabel: "late leftward force toward lateral leads", predictions: [{ lead: "V1", expected: "negative" }, { lead: "V6", expected: "positive" }], feedback: s1fb, accessibility: ax("A left-bundle-delay model with a terminal force away from V1 and toward V6.") }),
];

const s2fb = fb(
  "QRS [QRS] ms, terminal positivity in V1/V2, and a broad terminal S in I/V6 together support the appropriately complete or incomplete RBBB label.",
  "You found one terminal anchor. Confirm the same late force from the paired lateral view.",
  "Equal width or a ‘rabbit ears’ phrase is not enough. Demonstrate the paired terminal-force evidence.",
  "Pause at the tracing. This checkpoint grades RBBB morphology, not management. Complete both lead regions.",
  "The contract includes QRS duration and paired-lead morphology. RBBB is assessable.",
  "Find the last positive force in V1/V2 and the last negative force in I/V6.",
);
const s2i: LearningInteraction[] = [
  compactInteraction({ id: "m05-s2-qrs", kind: "caliper", prompt: "Measure QRS before naming complete or incomplete RBBB.", instructions: "Use onset to final return to baseline.", subskills: ["measure"], measurement: "qrs", target: { source: "packet_measurement", measurementKey: "qrs_ms", toleranceMs: 25, lead: "V1" }, requireBoundaryLabels: true, feedback: s2fb, accessibility: ax("QRS-duration measurement determining complete versus incomplete adult RBBB range.") }),
  compactInteraction({ id: "m05-s2-v1", kind: "region", prompt: "Box the terminal positive deflection in V1 or V2.", instructions: "Mark the final R-prime/terminal positive force, not the initial R.", subskills: ["localize"], concept: "rbbb_terminal_positive", allowedLeads: ["V1", "V2"], feedback: s2fb, accessibility: ax("A selectable terminal-positive QRS region in V1 or V2.") }),
  compactInteraction({ id: "m05-s2-lateral", kind: "region", prompt: "Box the broad terminal S in lead I or V6.", instructions: "Use the paired lateral view to confirm the late rightward force.", subskills: ["localize", "discriminate"], concept: "rbbb_terminal_s", allowedLeads: ["I", "V6"], feedback: s2fb, accessibility: ax("A selectable broad terminal-S region in lead I or V6.") }),
];

const s3fb = fb(
  "QRS [QRS] ms, predominantly negative V1, a broad lateral R, and secondary ST-T discordance support LBBB.",
  "You have width and one anchor. Add the paired lateral or right-precordial morphology.",
  "RBBB ends toward V1; this pattern’s broad terminal force is lateral and V1 is predominantly negative.",
  "Pause at the tracing. This checkpoint grades LBBB morphology and recovery direction, not management.",
  "LBBB morphology is assessable; primary ischemia is intentionally not assessed in this scene.",
  "Compare V1 with V6 before interpreting the recovery direction.",
);
const s3i: LearningInteraction[] = [
  compactInteraction({ id: "m05-s3-qrs", kind: "caliper", prompt: "Measure the QRS before applying LBBB morphology.", instructions: "Span onset to final return to baseline.", subskills: ["measure"], measurement: "qrs", target: { source: "packet_measurement", measurementKey: "qrs_ms", toleranceMs: 25, lead: "V1" }, requireBoundaryLabels: true, feedback: s3fb, accessibility: ax("A labeled QRS-duration measurement for the LBBB case.") }),
  compactInteraction({ id: "m05-s3-v1", kind: "region", prompt: "Box the predominantly negative right-precordial QRS.", instructions: "Use V1, not an isolated notch elsewhere.", subskills: ["localize"], concept: "lbbb_v1_negative", allowedLeads: ["V1", "V2"], feedback: s3fb, accessibility: ax("A selectable predominantly negative QRS region in V1 or V2.") }),
  compactInteraction({ id: "m05-s3-lateral", kind: "region", prompt: "Box the broad or notched lateral R.", instructions: "Use I, aVL, V5, or V6.", subskills: ["localize", "discriminate"], concept: "lbbb_lateral_r", allowedLeads: ["I", "aVL", "V5", "V6"], feedback: s3fb, accessibility: ax("A selectable broad lateral-R region.") }),
];

const s4fb = fb(
  "The case is correctly classified as RBBB, LBBB, nonspecific IV delay, or a wide QRS whose specific pattern is not assessable.",
  "Width is supported; the paired-lead evidence or evidence limit remains incomplete.",
  "Nonspecific delay requires a complete lead set that fails bundle criteria; missing required leads support a limited statement instead.",
  "Pause at the tracing. This checkpoint grades conduction morphology, not treatment.",
  "Use ‘specific pattern not assessable’ only when a required readable lead is unavailable, not when complete leads support nonspecific delay.",
  "Fill V1/V2 and lateral evidence rows before choosing the label.",
);
const s4i: LearningInteraction[] = [
  compactInteraction({ id: "m05-s4-qrs", kind: "caliper", prompt: "Measure QRS in each contrast case.", instructions: "Width is the first evidence row.", subskills: ["measure"], measurement: "qrs", target: { source: "packet_measurement", measurementKey: "qrs_ms", toleranceMs: 25, lead: "V1" }, requireBoundaryLabels: true, feedback: s4fb, accessibility: ax("QRS width for each right, left, nonspecific, or evidence-limited case.") }),
  compactInteraction({ id: "m05-s4-compare", kind: "compare", prompt: "Fill both lead rows before choosing right, left, nonspecific, or limited.", instructions: "Compare right-precordial and lateral terminal forces.", subskills: ["discriminate", "calibrate_confidence"], leftCaseConcept: "bundle_specific", rightCaseConcept: "nonspecific_or_limited", dimensions: [{ id: "v1", label: "V1/V2 terminal evidence", leftAnswer: "Terminal right-precordial force matches an authored bundle anchor", rightAnswer: "Required morphology is absent or the lead is unreadable" }, { id: "lateral", label: "Lateral terminal evidence", leftAnswer: "A paired lateral terminal-force anchor supports the same bundle pattern", rightAnswer: "Paired bundle criteria are absent or unavailable" }, { id: "claim", label: "Claim ceiling", leftAnswer: "Name the specific bundle pattern only when both anchors support it", rightAnswer: "Use nonspecific delay or state that the pattern is not assessable" }], feedback: s4fb, accessibility: ax("A semantic evidence board contrasting bundle-specific, nonspecific, and unavailable evidence.") }),
];

const s5fb = fb(
  "The fascicle model redirects the frontal vector and produces the compatible limb-lead pattern; the real-case claim remains limited by alternative causes.",
  "Axis is necessary but not sufficient. Add compatible limb-lead morphology.",
  "Axis deviation has multiple causes. Do not turn the axis alone into a fascicular diagnosis.",
  "Pause at the tracing. This checkpoint grades vector redirection, not management.",
  "On a real case without compatible morphology or exclusion evidence, keep the axis description rather than forcing a fascicle.",
  "Reuse lead I, aVF, and lead II, then inspect the limb-lead QRS pattern.",
);
const s5i: LearningInteraction[] = [
  compactInteraction({ id: "m05-s5-axis", kind: "vector_lab", prompt: "Disable one fascicle and match the redirected frontal vector.", instructions: "Rotate the axis until limb-lead polarity matches the teaching model.", subskills: ["explain_mechanism", "measure"], initialAngleDeg: 60, targetAngleDeg: -55, toleranceDeg: 15, targetLabel: "left-anterior-fascicle teaching vector", predictions: [{ lead: "I", expected: "positive" }, { lead: "aVF", expected: "negative" }], feedback: s5fb, accessibility: ax("A numeric axis control and limb-lead polarity table for fascicular redirection.") }),
  compactInteraction({ id: "m05-s5-leads", kind: "lead_select", prompt: "Select the limb leads that support the fascicular pattern.", instructions: "Use axis plus compatible QRS morphology, not axis alone.", subskills: ["localize", "discriminate"], selectionMode: "multiple", correctLeads: ["I", "II", "III", "aVL", "aVF"], allowedLeads: ["I", "II", "III", "aVR", "aVL", "aVF"], rejectExtraSelections: true, feedback: s5fb, accessibility: ax("Named limb-lead buttons supporting axis and fascicular morphology review.") }),
];

const s6fb = fb(
  "The tracing supports RBBB, a fascicular pattern, and first-degree AV block as separate findings; it does not prove the extra anatomy implied by ‘trifascicular block.’",
  "Some components are verified. Measure and mark the missing component before editing that phrase.",
  "A long PR does not localize delay to the remaining fascicle. Preserve the demonstrated components and strike the unsupported umbrella label.",
  "Pause at the tracing. This checkpoint grades the machine statement, not pacing decisions.",
  "The case contract provides RBBB, axis, and PR evidence; those components are assessable separately.",
  "Verify RBBB, then axis/fascicular evidence, then PR—three separate checks.",
);
const s6i: LearningInteraction[] = [
  compactInteraction({ id: "m05-s6-rbbb-region", kind: "region", prompt: "Mark the paired RBBB terminal morphology.", instructions: "Verify the first component before auditing the machine sentence.", subskills: ["localize", "discriminate"], concept: "rbbb_terminal_pattern", allowedLeads: ["V1", "V2", "I", "V6"], feedback: s6fb, accessibility: ax("RBBB terminal regions in a right-precordial and lateral lead.") }),
  compactInteraction({ id: "m05-s6-pr", kind: "caliper", prompt: "Measure PR as a separate conduction component.", instructions: "Do not use long PR to localize delay to a specific fascicle.", subskills: ["measure"], measurement: "pr", target: { source: "packet_measurement", measurementKey: "pr_ms", toleranceMs: 30, lead: "II" }, requireBoundaryLabels: true, feedback: s6fb, accessibility: ax("A separate PR measurement for the combined-conduction case.") }),
  compactInteraction({ id: "m05-s6-audit", kind: "multi_select", prompt: "Audit each phrase against the waveform.", instructions: "Select the evidence-backed component phrases and reject the unsupported umbrella term.", subskills: ["synthesize", "calibrate_confidence"], options: [{ id: "rbbb", label: "RBBB", rationale: "Supported by paired morphology." }, { id: "lafb", label: "Left anterior fascicular-block pattern", rationale: "Supported by axis and limb morphology." }, { id: "first", label: "First-degree AV block", rationale: "Supported by long, one-to-one PR." }, { id: "trifascicular", label: "Trifascicular block", rationale: "Not proven by these components alone." }], correctOptionIds: ["rbbb", "lafb", "first"], rejectExtraSelections: true, feedback: s6fb, accessibility: ax("Four machine-statement phrases with Supported by waveform or Not supported controls.") }),
];

const s7fb = fb(
  "PR [PR] ms, a delta wave, and QRS [QRS] ms together support a pre-excitation/WPW pattern.",
  "One finding is present, but the complete pattern requires short PR, initial QRS slur, and widened fused QRS.",
  "BBB changes terminal activation. Pre-excitation announces itself at the beginning with the delta wave and short PR.",
  "Pause at the tracing. This checkpoint grades the pre-excitation pattern, not treatment.",
  "The eligible case provides PR/QRS measurements and a visible delta-wave ROI; the pattern is assessable.",
  "Inspect the beginning of QRS, not only total width.",
);
const s7i: LearningInteraction[] = [
  compactInteraction({ id: "m05-s7-pr", kind: "caliper", prompt: "Measure the PR interval in the pre-excitation case.", instructions: "Use P onset to the first QRS slur.", subskills: ["measure"], measurement: "pr", target: { source: "packet_measurement", measurementKey: "pr_ms", toleranceMs: 25, lead: "II" }, requireBoundaryLabels: true, feedback: s7fb, accessibility: ax("A short-PR measurement ending at the earliest QRS onset.") }),
  compactInteraction({ id: "m05-s7-delta", kind: "region", prompt: "Outline the delta wave—the slurred initial QRS.", instructions: "Mark the beginning, not a terminal bundle force.", subskills: ["localize", "discriminate"], concept: "delta_wave", allowedLeads: ["I", "II", "V2", "V4", "V5"], feedback: s7fb, accessibility: ax("A selectable initial-QRS slur in the clearest eligible lead.") }),
  compactInteraction({ id: "m05-s7-qrs", kind: "caliper", prompt: "Measure the complete fused QRS.", instructions: "Include the delta-wave onset through final QRS return.", subskills: ["measure"], measurement: "qrs", target: { source: "packet_measurement", measurementKey: "qrs_ms", toleranceMs: 25 }, requireBoundaryLabels: true, feedback: s7fb, accessibility: ax("A fused-QRS duration measurement beginning at the delta-wave onset.") }),
];

const s8fb = fb(
  "Each spike is linked to the electrical event that follows, with capture and sensing kept as separate questions.",
  "The spike is found, but its response row is incomplete. Link it to P, QRS, or no captured response.",
  "A real tracing can support paced morphology without supporting a device-malfunction diagnosis; use the reviewed simulation for capture and sensing.",
  "Device settings and management require the device record and clinical team. Complete the electrical spike-to-response evidence.",
  "On a real tracing without visible spikes, spike timing may be not assessable; the authored core model makes all required events explicit.",
  "Build one ledger row per spike: timing, followed event, capture, and sensing note.",
);
const s8i: LearningInteraction[] = [
  compactInteraction({ id: "m05-s8-spikes", kind: "point", prompt: "Find every pacing spike and link it to the electrical event that follows.", instructions: "Mark spike timing before deciding chamber or capture.", subskills: ["localize", "discriminate"], concept: "pacing_spike", gradePrompt: "Grade every selected point against authored spike times or reviewed packet markers.", allowedLeads: ["II", "V1", "V6"], feedback: s8fb, accessibility: ax("A spike ledger with time and the next P wave, QRS, or absent response.") }),
  compactInteraction({ id: "m05-s8-pairing", kind: "pairing", prompt: "Pair each pacing spike with the event that follows.", instructions: "Use P wave, paced QRS, or no captured response; do not infer programming mode.", subskills: ["discriminate"], left: [{ id: "spike-a", label: "Spike A" }, { id: "spike-v", label: "Spike V" }, { id: "spike-f", label: "Spike F" }], right: [{ id: "p-wave", label: "P wave" }, { id: "paced-qrs", label: "Paced QRS" }, { id: "none", label: "No captured response" }], correctPairs: { "spike-a": "p-wave", "spike-v": "paced-qrs", "spike-f": "none" }, feedback: s8fb, accessibility: ax("Three spike-to-response pairing rows for atrial capture, ventricular capture, and no capture.") }),
  compactInteraction({ id: "m05-s8-ledger", kind: "multi_select", prompt: "Complete the spike-to-response ledger for the active simulation.", instructions: "Select only the statements demonstrated by the authored events.", subskills: ["discriminate", "synthesize"], options: [{ id: "atrial", label: "Atrial spike followed by P wave", rationale: "Atrial capture." }, { id: "ventricular", label: "Ventricular spike followed by paced QRS", rationale: "Ventricular capture." }, { id: "failure", label: "Spike with no captured electrical response", rationale: "Failure to capture in the authored simulation." }, { id: "mode", label: "The exact programmed device mode is proven", rationale: "Requires device records." }], correctOptionIds: ["atrial", "ventricular", "failure"], rejectExtraSelections: true, feedback: s8fb, accessibility: ax("A semantic table of spike timing and captured response.") }),
];

const s9fb = fb(
  "The QRS and T directions demonstrate expected secondary discordance, while the superimposed region remains marked for separate assessment.",
  "One direction is correct; mark the dominant QRS before comparing T.",
  "Expected discordance is context, not a universal exclusion rule. Do not dismiss a superimposed change.",
  "This scene does not supply criteria or context for an acute diagnosis. Complete the direction comparison.",
  "QRS/T polarity is assessable in the selected leads; etiology beyond secondary change is intentionally not assessed.",
  "Name depolarization first, recovery second, then compare their directions.",
);
const s9i: LearningInteraction[] = [
  compactInteraction({ id: "m05-s9-stt-region", kind: "region", prompt: "Mark the recovery region after the altered QRS.", instructions: "Select ST/T only after identifying the dominant QRS direction.", subskills: ["localize"], concept: "secondary_st_t_region", allowedLeads: ["V1", "V6", "I"], feedback: s9fb, accessibility: ax("Named QRS and T regions with textual polarity labels.") }),
  compactInteraction({ id: "m05-s9-direction", kind: "compare", prompt: "Mark QRS direction, mark T direction, then compare them.", instructions: "Use dominant QRS polarity and classify recovery as concordant, discordant, or unclear.", subskills: ["discriminate", "explain_mechanism"], leftCaseConcept: "altered_depolarization", rightCaseConcept: "secondary_repolarization", dimensions: [{ id: "direction", label: "Dominant direction", leftAnswer: "Record dominant QRS polarity in the selected lead", rightAnswer: "Record T-wave polarity in that same lead" }, { id: "relationship", label: "Relationship", leftAnswer: "Altered ventricular activation establishes the primary vector", rightAnswer: "Secondary recovery is often discordant to the dominant QRS" }, { id: "limit", label: "Superimposed change", leftAnswer: "Mark any disproportionate primary ST-T change separately", rightAnswer: "Do not dismiss a change that fails the expected secondary pattern" }], feedback: s9fb, accessibility: ax("A lead-by-lead text comparison of QRS and T polarity plus an evidence-limit row.") }),
];

const s10fb = fb(
  "Duration, paired morphology, and the additional initial-QRS or spike evidence support the strongest defensible pathway classification.",
  "Some evidence is credited; the conclusion remains locked until the missing waveform action is complete.",
  "Recompare the right-precordial and lateral terminal forces, then inspect initial QRS and pacing spikes before choosing nonspecific delay.",
  "Pause at the tracing. This exit grades activation and morphology, not device or drug management.",
  "Use a limited statement only when the required lead or evidence is genuinely unavailable.",
  "QRS duration → V1/V2 → I/aVL/V5/V6 → axis → PR/initial QRS → pacing spikes → recovery.",
);
const s10i: LearningInteraction[] = [
  compactInteraction({ id: "m05-s10-qrs", kind: "caliper", prompt: "Run the eight-step activation order: start with QRS width.", instructions: "Measure before searching for morphology anchors.", subskills: ["measure"], measurement: "qrs", target: { source: "packet_measurement", measurementKey: "qrs_ms", toleranceMs: 25 }, requireBoundaryLabels: true, feedback: s10fb, accessibility: ax("An independent QRS measurement on an unannounced pathway case.") }),
  compactInteraction({ id: "m05-s10-leads", kind: "lead_select", prompt: "Select the decisive right-precordial and lateral leads.", instructions: "Choose only leads containing the packet’s validated morphology evidence.", subskills: ["localize", "discriminate"], selectionMode: "multiple", correctLeads: ["V1", "V6"], allowedLeads: ["I", "II", "aVL", "V1", "V2", "V5", "V6"], feedback: s10fb, accessibility: ax("Named lead selectors for the decisive paired morphology.") }),
  compactInteraction({ id: "m05-s10-synthesis", kind: "free_response", prompt: "Submit the strongest defensible activation conclusion and confidence.", instructions: "Include duration, paired morphology, and delta/spike evidence when relevant.", subskills: ["synthesize", "calibrate_confidence"], responseLabel: "Activation conclusion", placeholder: "QRS … with …", minimumCharacters: 45, rubric: [{ id: "width", label: "Includes QRS duration class", acceptedConcepts: ["wide", "narrow", "milliseconds", "ms"], required: true }, { id: "pathway", label: "Names supported pathway or evidence limit", acceptedConcepts: ["RBBB", "LBBB", "nonspecific", "pre-excitation", "paced", "not assessable"], required: true, misconceptionIfMissing: "wide_qrs_pathway_missing" }], feedback: s10fb, accessibility: ax("A concise width-plus-morphology conclusion with calibrated confidence.") }),
];

export const M05_VENTRICULAR_CONDUCTION_MODULE: ProductionModule = {
  id: "ventricular-conduction",
  order: 5,
  title: "Ventricular Activation, Conduction Delay, Pre-excitation, and Pacing",
  shortTitle: "Ventricular conduction",
  duration: "65–80 min",
  outcome: "Reason from QRS duration and paired-lead morphology through bundle/fascicular delay, nonspecific delay, pre-excitation, pacing, and secondary recovery change.",
  prerequisiteIds: ["leads-vectors", "av-brady"],
  accent: "#7655B7",
  sourceRequirementIds: ["SPEC-11.7", "SPEC-11.8", "SPEC-7.qrs_duration", "SPEC-16.rbbb_lbbb_confusion", "ACC18-CONDUCTION"],
  scenes: [
    buildScene({ id: "m05-s0", partId: "m05-part-1", minutes: 5, source: sources("M5-S0", ["SPEC-11.7", "SPEC-8.5", "FOUND-S6"]), copy: sceneCopy({ eyebrow: "M5 · 1 of 11", title: "Width is not morphology", objective: "Answer two separate questions: how long, and what shape?", openingTutorMessage: "Measure the active tracing first. Then use a separate teaching model to predict where a late rightward force points in V1 and V6.", setup: ["QRS duration asks how long ventricular activation took. Morphology asks how activation traveled and where its forces pointed."], mechanismNarration: ["Two QRS complexes can have the same width and different pathways. A specific conduction label needs both. This scene measures one real QRS, then models terminal polarity without pretending the model is patient-trace localization."], clinicalConnectionHeading: "Evidence before specificity", clinicalConnectionBody: "A wide QRS alone is not a bundle diagnosis.", transitionIntoTask: "Measure the active tracing, then predict paired polarity in the authored model.", completionBody: "A real duration measurement and an authored morphology mechanism are now separate evidence dimensions." }), layout: responsiveLayout("A full calibrated tracing supports the QRS measurement; a separate V1/V6 vector model supports terminal-polarity prediction. Mobile keeps each activity full width."), tutor: tutorContract({ socratic: "If duration is identical, what waveform evidence can still separate activation paths?", hints: ["Use QRS onset to final return to baseline.", "In the teaching model, predict the terminal—not merely tallest—QRS direction in V1 and V6."], tangentBridge: "I’ll preserve the real calipers and the separate model state.", returnPrompt: "Back to the active task: finish the real width before the modeled terminal-force prediction." }), caseContract: caseSpec({ selectorLessonId: "qrs-conduction", requestedConcept: "qrs_duration", minimumTier: "A", requiredEvidence: ["QRS onset/end", "QRS duration", "Authored V1/V6 terminal-force prediction"], requiredLeads: ["V1", "I", "V6"], allowedUses: ["measurement", "mechanism", "scored_recognition"], fallback: "authored_simulation", forbiddenClaims: ["Bundle label from width alone", "Patient-trace localization credit from the teaching model"] }), interactions: s0i, minimumScore: 0.9, connections: { recallFrom: "Foundations QRS boundaries and M2 vectors", changesNow: "Real duration evidence and authored morphology mechanics become separate questions", reuseNext: "Every M5 pathway and M6 WCT", clinicalUse: "Prevents wide-equals-BBB shortcuts and model-to-patient evidence leakage" }, handoffs: [handoff("train", "Train · Width versus morphology", "qrs_width_morphology", "discriminate", "guided")] }),
    buildScene({ id: "m05-s1", partId: "m05-part-1", minutes: 5, source: sources("M5-S1", ["SPEC-11.7", "SPEC-11.8", "M2-AXIS"]), copy: sceneCopy({ eyebrow: "M5 · 2 of 11", title: "Block a branch, move the final force", objective: "Derive bundle morphology from the delayed ventricle.", openingTutorMessage: "Do not memorize a letter shape yet. Ask which ventricle finishes last and where the final force points.", setup: ["With both bundles conducting, the ventricles activate rapidly together."], mechanismNarration: ["If one bundle is delayed, the other ventricle activates first; the last QRS force points toward the ventricle activated last."], clinicalConnectionHeading: "Mechanism before mnemonic", clinicalConnectionBody: "Terminal-force direction explains variant shapes better than a single nickname.", transitionIntoTask: "Predict the final force before you scrub the activation.", completionBody: "Both bundle-delay models now connect the delayed ventricle to terminal lead polarity." }), layout: responsiveLayout("The conduction tree, V1, V6, and live strip remain synchronized; mobile uses three numbered frames."), tutor: tutorContract({ socratic: "If the right ventricle is activated last, which precordial lead sits closest to that terminal force?", hints: ["V1 is right/anterior; V6 is left/lateral.", "Right-bundle delay creates a late rightward force; left-bundle delay creates a late leftward force."], tangentBridge: "I’ll freeze the wavefront at the current frame.", returnPrompt: "Back to the wavefront: place the terminal-force arrow before scrubbing." }), caseContract: caseSpec({ selectorLessonId: "bundle-branch-blocks", requestedConcept: "bundle_activation_model", minimumTier: "A", requiredEvidence: ["Authored activation sequence", "V1/V6 projections", "QRS onset/end"], requiredLeads: ["V1", "V6"], allowedUses: ["mechanism"], fallback: "authored_simulation", forbiddenClaims: ["Patient-specific diagnosis from the model"] }), interactions: s1i, minimumScore: 0.9, connections: { recallFrom: "M2 vector projection", changesNow: "Terminal QRS forces are derived from activation order", reuseNext: "RBBB and LBBB anchors", clinicalUse: "Explains bundle morphology variants" }, handoffs: [handoff("train", "Train · Terminal-force prediction", "bundle_activation", "explain_mechanism", "guided")] }),
    buildScene({ id: "m05-s2", partId: "m05-part-2", minutes: 6, source: sources("M5-S2", ["SPEC-11.8", "SPEC-7.right_bundle_branch_block", "ACC18-CONDUCTION"]), copy: sceneCopy({ eyebrow: "M5 · 3 of 11", title: "Right bundle-branch block", objective: "Use duration plus paired V1/lateral morphology.", openingTutorMessage: "Measure first. Then box the last force in a right precordial lead and a lateral lead.", setup: ["Adult complete RBBB requires QRS at least 120 ms plus compatible morphology."], mechanismNarration: ["Late rightward force often produces terminal R′ in V1/V2 and broad terminal S in I/V6. QRS 110–119 ms with compatible morphology is incomplete RBBB in the referenced adult guideline."], clinicalConnectionHeading: "Shape varies", clinicalConnectionBody: "Paired terminal direction is stronger than the phrase rabbit ears.", transitionIntoTask: "Prove RBBB with duration and paired terminal-force evidence.", completionBody: "Duration and both terminal anchors support complete or incomplete RBBB." }), layout: responsiveLayout("Linked V1/V6 magnifiers dominate; lead I remains a confirmation strip."), tutor: tutorContract({ socratic: "Do terminal deflections point toward V1 and away from V6 as delayed RV activation predicts?", hints: ["The terminal deflection is the last part before QRS returns to baseline.", "Use V1/V2 for terminal positivity and I/V6 for broad terminal S."], tangentBridge: "I’ll preserve both lead boxes and calipers.", returnPrompt: "Back to RBBB evidence: finish both lead boxes before naming complete or incomplete." }), caseContract: caseSpec({ selectorLessonId: "bundle-branch-blocks", requestedConcept: "right_bundle_branch_block", minimumTier: "A", requiredEvidence: ["QRS duration", "Compatible RBBB statement", "Terminal R-prime in V1/V2", "Terminal S in I/V6"], requiredLeads: ["V1", "V2", "I", "V6"], allowedUses: ["measurement", "scored_recognition"], fallback: "authored_simulation", forbiddenClaims: ["RBBB from mnemonic alone", "Complete/incomplete without width"] }), interactions: s2i, minimumScore: 0.9, connections: { recallFrom: "M5-S1 terminal rightward force", changesNow: "Mechanism becomes real paired-lead evidence", reuseNext: "BBB contrast and WCT", clinicalUse: "Recognizes RBBB variants without mnemonic dependence" }, handoffs: [handoff("train", "Train · RBBB anchors", "right_bundle_branch_block", "discriminate", "faded")] }),
    buildScene({ id: "m05-s3", partId: "m05-part-2", minutes: 6, source: sources("M5-S3", ["SPEC-11.8", "SPEC-7.left_bundle_branch_block", "ACC18-CONDUCTION"]), copy: sceneCopy({ eyebrow: "M5 · 4 of 11", title: "Left bundle-branch block", objective: "Show the broad lateral force and expected secondary discordance.", openingTutorMessage: "Build LBBB from activation first. Recovery stays hidden until QRS evidence is complete.", setup: ["Adult complete LBBB requires QRS at least 120 ms plus compatible morphology."], mechanismNarration: ["A broad/notched lateral R and predominantly negative right-precordial QRS reflect delayed leftward activation. Recovery often points opposite the main QRS."], clinicalConnectionHeading: "Secondary discordance has limits", clinicalConnectionBody: "Expected recovery direction does not prove every ST-T change is benign.", transitionIntoTask: "Prove LBBB from V1 and a lateral lead, then compare recovery.", completionBody: "Duration and paired morphology support LBBB; ischemia remains outside this scene’s claim." }), layout: responsiveLayout("V1 and V6 share a cursor; a lateral carousel and recovery overlay unlock after QRS evidence."), tutor: tutorContract({ socratic: "If the left ventricle finishes last, where should the broad terminal force appear?", hints: ["Compare V1 with V6 rather than one notch.", "After the wide QRS, ask whether ST/T points secondarily opposite the dominant QRS."], tangentBridge: "I’ll keep recovery hidden and preserve QRS marks.", returnPrompt: "Back to LBBB evidence: box the lateral R, then inspect recovery." }), caseContract: caseSpec({ selectorLessonId: "bundle-branch-blocks", requestedConcept: "left_bundle_branch_block", minimumTier: "A", requiredEvidence: ["QRS duration", "Compatible LBBB statement", "Predominantly negative V1", "Broad lateral R", "QRS/T polarity"], requiredLeads: ["V1", "I", "aVL", "V5", "V6"], allowedUses: ["measurement", "scored_recognition"], fallback: "authored_simulation", forbiddenClaims: ["Ischemia called or excluded from secondary discordance"] }), interactions: s3i, minimumScore: 0.9, connections: { recallFrom: "M5-S1 terminal leftward force", changesNow: "Mechanism becomes paired-lead LBBB evidence", reuseNext: "Nonspecific delay and secondary ST-T", clinicalUse: "Avoids mistaking LBBB recovery for automatic acute injury" }, handoffs: [handoff("train", "Train · LBBB anchors", "left_bundle_branch_block", "discriminate", "faded")] }),
    buildScene({ id: "m05-s4", partId: "m05-part-2", minutes: 6, source: sources("M5-S4", ["SPEC-11.7", "SPEC-7.nonspecific_intraventricular_conduction_delay", "ACC18-CONDUCTION"]), copy: sceneCopy({ eyebrow: "M5 · 5 of 11", title: "Right, left, or neither?", objective: "Use the strongest defensible conduction label.", openingTutorMessage: "No label until both right-precordial and lateral evidence rows are filled.", setup: ["A wide QRS is not automatically RBBB or LBBB."], mechanismNarration: ["When QRS is prolonged but neither pattern is supported, use nonspecific IV delay; when required leads are unavailable, limit the claim to wide QRS with specific pattern not assessable."], clinicalConnectionHeading: "Absence versus missingness", clinicalConnectionBody: "Criteria absent in readable leads differs from criteria unavailable because a lead is unreadable.", transitionIntoTask: "Fill both lead rows before choosing right, left, nonspecific, or limited.", completionBody: "Bundle-specific, nonspecific, and evidence-limited categories are now separated." }), layout: responsiveLayout("Four ECG cards surround a semantic evidence board; mobile pins the board under one active card."), tutor: tutorContract({ socratic: "Which required anchor is missing—and is it absent or unavailable?", hints: ["A complete case has required leads and clear morphology.", "Nonspecific delay is positive only when width is real and bundle criteria are not met."], tangentBridge: "I’ll preserve the evidence board and active card.", returnPrompt: "Back to case [n]: fill both lead rows before choosing the label." }), caseContract: caseSpec({ selectorLessonId: "bundle-branch-blocks", requestedConcept: "nonspecific_intraventricular_conduction_delay", minimumTier: "A", requiredEvidence: ["QRS >110 ms", "No full RBBB/LBBB criteria", "Readable paired leads", "Limited-case missingness flag"], requiredLeads: ["V1", "V2", "I", "aVL", "V5", "V6"], allowedUses: ["scored_recognition", "transfer"], fallback: "authored_simulation", forbiddenClaims: ["Specific BBB without morphology", "Nonspecific IVCD when evidence is merely unavailable"] }), interactions: s4i, minimumScore: 0.85, connections: { recallFrom: "M5-S2/S3 paired anchors", changesNow: "Neither and unavailable become distinct outcomes", reuseNext: "M5 exit and M6 WCT claim strength", clinicalUse: "Supports honest wide-QRS communication" }, handoffs: [handoff("train", "Train · BBB versus nonspecific delay", "ivcd_claim_strength", "calibrate_confidence", "faded")] }),
    buildScene({ id: "m05-s5", partId: "m05-part-3", minutes: 6, source: sources("M5-S5", ["SPEC-11.6", "M2-AXIS", "ACC18-CONDUCTION"]), copy: sceneCopy({ eyebrow: "M5 · 6 of 11", title: "Fascicles redirect the frontal vector", objective: "Use axis as mechanistic evidence, not a memorized suffix.", openingTutorMessage: "Turn off one route and follow where activation must travel first and last.", setup: ["The left bundle divides into fascicles. Losing one route redirects ventricular activation through the remaining route and shifts frontal QRS axis."], mechanismNarration: ["Axis is necessary evidence for a fascicular pattern, but alternative causes must still be considered."], clinicalConnectionHeading: "Axis is not anatomy alone", clinicalConnectionBody: "A specific real-case label requires compatible axis, morphology, and grounded support.", transitionIntoTask: "Redirect the vector through the remaining fascicle and match the limb leads.", completionBody: "The fascicle model now explains the axis shift without overcalling real cases." }), layout: responsiveLayout("Hexaxial wheel, limb-lead stack, and conduction-tree inset remain linked."), tutor: tutorContract({ socratic: "Does the axis shift because of a memorized name, or because the remaining route redirects the net vector?", hints: ["Reuse lead I and aVF; lead II refines the leftward boundary.", "A fascicular label needs compatible axis and morphology after alternatives are considered."], tangentBridge: "I’ll preserve axis angle and selected leads.", returnPrompt: "Back to the hexaxial wheel: match limb-lead polarities before naming a fascicle." }), caseContract: caseSpec({ selectorLessonId: "fascicular-preexcitation", requestedConcept: "left_anterior_fascicular_block", minimumTier: "A", requiredEvidence: ["Measured axis", "Compatible limb morphology", "Explicit fascicular support"], requiredLeads: ["I", "II", "III", "aVL", "aVF"], allowedUses: ["mechanism", "scored_recognition"], fallback: "authored_simulation", forbiddenClaims: ["Fascicular block from axis alone", "LPFB competency without eligible case"] }), interactions: s5i, minimumScore: 0.85, connections: { recallFrom: "M2 axis and vector projection", changesNow: "Axis shift is derived from fascicular redirection", reuseNext: "Combined conduction and chamber patterns", clinicalUse: "Prevents axis-only fascicular labels" }, handoffs: [handoff("train", "Train · Fascicular axis", "left_anterior_fascicular_block", "explain_mechanism", "guided")] }),
    buildScene({ id: "m05-s6", partId: "m05-part-3", minutes: 6, source: sources("M5-S6", ["SPEC-11.7", "SPEC-11.8", "ACC18-CONDUCTION"]), copy: sceneCopy({ eyebrow: "M5 · 7 of 11", title: "Combined conduction: assemble, do not overname", objective: "Build combined patterns from independently proven components.", openingTutorMessage: "Audit the machine one component at a time. Do not accept or reject the whole sentence at once.", setup: ["A bifascicular pattern combines RBBB with a compatible left fascicular block."], mechanismNarration: ["A long PR adds AV-conduction delay, but first-degree AV block plus bifascicular morphology does not itself prove trifascicular block."], clinicalConnectionHeading: "Describe demonstrated components", clinicalConnectionBody: "Syncope plus conduction disease changes concern, but ECG cannot establish the cause of syncope alone.", transitionIntoTask: "Audit each phrase against the waveform.", completionBody: "Supported components are preserved and the unsupported umbrella label is removed." }), layout: responsiveLayout("Full 12-lead sits above a phrase-level machine-audit card."), tutor: tutorContract({ socratic: "What anatomical claim does trifascicular add that this surface ECG has not proven?", hints: ["Verify RBBB, then axis/fascicular evidence, then PR.", "A prolonged PR can reflect delay at more than one level."], tangentBridge: "I’ll preserve every supported/unsupported phrase state.", returnPrompt: "Back to the machine statement: support or strike each phrase from waveform evidence." }), caseContract: caseSpec({ selectorLessonId: "fascicular-preexcitation", requestedConcept: "bifascicular_conduction_pattern", minimumTier: "A", requiredEvidence: ["RBBB contract", "Axis", "Fascicular morphology", "PR measurement"], requiredLeads: ["II", "V1", "V6", "I", "aVF"], allowedUses: ["transfer", "measurement"], fallback: "authored_simulation", forbiddenClaims: ["Trifascicular block from long PR plus bifascicular pattern", "Syncope cause"] }), interactions: s6i, minimumScore: 0.85, connections: { recallFrom: "M4 first-degree and M5 RBBB/fascicles", changesNow: "Components are assembled without overnamed anatomy", reuseNext: "Machine-audit and integrated interpretation", clinicalUse: "Communicates conduction disease precisely" }, handoffs: [handoff("train", "Train · Audit the machine read", "machine_audit_conduction", "synthesize", "faded")], }),
    buildScene({ id: "m05-s7", partId: "m05-part-3", minutes: 7, source: sources("M5-S7", ["SPEC-11.7", "CLIN-TABLE.wolff_parkinson_white", "ACC23-AF"]), copy: sceneCopy({ eyebrow: "M5 · 8 of 11", title: "Pre-excitation: the shortcut changes the beginning", objective: "Connect short PR, delta wave, and fused wide QRS to early activation.", openingTutorMessage: "Change when the shortcut arrives. Watch the beginning of QRS, not only its total width.", setup: ["An accessory pathway can bypass normal AV delay and activate part of a ventricle early."], mechanismNarration: ["The ECG pattern combines short PR, a slurred initial QRS called delta wave, and a widened fused QRS."], clinicalConnectionHeading: "Pattern versus syndrome", clinicalConnectionBody: "The ECG supports a pre-excitation/WPW pattern; symptoms and documented tachyarrhythmia are needed for broader clinical claims.", transitionIntoTask: "Find short PR, delta wave, and fused QRS.", completionBody: "All three pre-excitation components are grounded on the waveform." }), layout: responsiveLayout("Dual-pathway model, magnified beat, and normal/accessory timelines remain synchronized."), tutor: tutorContract({ socratic: "Why can activation begin early yet finish through a mixture of normal and accessory conduction?", hints: ["The delta wave is the slurred first portion of QRS.", "The complete pattern needs all three findings; one alone is nonspecific."], tangentBridge: "I’ll preserve shortcut timing and all boundaries.", returnPrompt: "Back to the shortcut: outline the initial slur before filling the evidence tray." }), caseContract: caseSpec({ selectorLessonId: "fascicular-preexcitation", requestedConcept: "wolff_parkinson_white", minimumTier: "A", requiredEvidence: ["Compatible pre-excitation statement", "PR and QRS measurements", "Visible delta morphology"], requiredLeads: ["II"], allowedUses: ["mechanism", "measurement", "scored_recognition"], fallback: "authored_simulation", forbiddenClaims: ["WPW syndrome without clinical tachyarrhythmia", "Pre-excitation from short PR alone"] }), interactions: s7i, minimumScore: 0.9, connections: { recallFrom: "M4 AV delay and M5 initial versus terminal QRS", changesNow: "An accessory shortcut changes QRS onset", reuseNext: "M6 irregular wide tachycardia", clinicalUse: "Recognizes pre-excitation before selecting tachycardia pathways" }, handoffs: [handoff("train", "Train · Delta-wave search", "wolff_parkinson_white", "localize", "faded")], }),
    buildScene({ id: "m05-s8", partId: "m05-part-4", minutes: 7, source: sources("M5-S8", ["CLIN-TABLE.paced_rhythm", "SPEC-16.paced_artifact_confusion"]), copy: sceneCopy({ eyebrow: "M5 · 9 of 11", title: "Pacing: ask four separate questions", objective: "Link each pacing spike to what follows.", openingTutorMessage: "Do not start with the device mode. Build the spike ledger one event at a time.", setup: ["A pacing spike is a timing marker, not a complete device interpretation."], mechanismNarration: ["Ask where the spike is timed, which chamber appears activated, whether it captures, and whether pacing responds appropriately to sensed beats."], clinicalConnectionHeading: "Device boundary", clinicalConnectionBody: "Programming and management require the device record and clinical team.", transitionIntoTask: "Find every spike and link it to the electrical event that follows.", completionBody: "Spike timing, chamber response, capture, and sensing are separated." }), layout: responsiveLayout("A rhythm strip sits above a semantic spike ledger; full 12-lead opens for paced morphology."), tutor: tutorContract({ socratic: "What electrical event follows this spike within the expected capture window?", hints: ["Atrial capture produces an atrial event; ventricular capture produces a paced QRS.", "Identify a native event before judging sensing in the authored simulation."], tangentBridge: "I’ll preserve every spike-ledger row.", returnPrompt: "Back to spike [n]: link it to the next electrical event." }), caseContract: caseSpec({ selectorLessonId: "paced", requestedConcept: "paced_rhythm", minimumTier: "A", requiredEvidence: ["Visible or authored spike times", "P/QRS response windows", "Reviewed capture/sensing truth"], requiredLeads: ["II", "V1", "V6"], allowedUses: ["mechanism", "scored_recognition"], fallback: "authored_simulation", forbiddenClaims: ["Real-device malfunction without reviewed evidence", "Programming advice"] }), interactions: s8i, minimumScore: 0.85, connections: { recallFrom: "M3 artifact and M5 pathway morphology", changesNow: "Device timing and electrical response become separate evidence rows", reuseNext: "Paced secondary ST-T and clinical device cases after review", clinicalUse: "Prevents paced rhythm from being mistaken for BBB or artifact" }, handoffs: [handoff("train", "Train · Spike-to-response ledger", "paced_rhythm", "discriminate", "guided")], }),
    buildScene({ id: "m05-s9", partId: "m05-part-4", minutes: 6, source: sources("M5-S9", ["SPEC-11.11", "SPEC-16.mi_overcall", "ARCH-M5"]), copy: sceneCopy({ eyebrow: "M5 · 10 of 11", title: "When activation changes recovery", objective: "Recognize secondary ST-T discordance without dismissing new findings.", openingTutorMessage: "Name depolarization first, recovery second. Then compare their directions.", setup: ["Abnormal ventricular activation changes the sequence of recovery."], mechanismNarration: ["In BBB and ventricular pacing, ST segments and T waves often point opposite the dominant QRS. Expected discordance explains part of the appearance; it does not make every superimposed change harmless."], clinicalConnectionHeading: "Context, not exclusion", clinicalConnectionBody: "Primary repolarization and ischemia require separate evidence in M8/M9.", transitionIntoTask: "Mark QRS direction, mark T direction, then compare them.", completionBody: "Secondary discordance is recognized while superimposed change remains open for assessment." }), layout: responsiveLayout("Each lead displays QRS and T direction sockets; a teaching-model subtraction is never applied to real data."), tutor: tutorContract({ socratic: "Does recovery fit altered activation, and is anything present that should not be dismissed as expected?", hints: ["Use the dominant QRS, not a small notch.", "Expected discordance is context, not a universal exclusion rule."], tangentBridge: "I’ll preserve QRS/T direction marks.", returnPrompt: "Back to [lead]: mark QRS direction before T direction." }), caseContract: caseSpec({ selectorLessonId: "bundle-branch-blocks", requestedConcept: "secondary_repolarization", minimumTier: "A", requiredEvidence: ["Eligible BBB or authored pacing", "Lead-specific QRS/T polarity", "Superimposed teaching ROI"], requiredLeads: ["V1", "V6", "I"], allowedUses: ["mechanism", "transfer"], fallback: "authored_simulation", forbiddenClaims: ["Ischemia called or excluded", "Superimposed change ignored"] }), interactions: s9i, minimumScore: 0.85, connections: { recallFrom: "M5-S3 LBBB recovery", changesNow: "Recovery is interpreted relative to activation", reuseNext: "M8 primary versus secondary and M9 mimics", clinicalUse: "Avoids both overcalling and dismissing ST-T change" }, handoffs: [handoff("train", "Train · Secondary repolarization", "secondary_repolarization", "discriminate", "faded")], }),
    buildScene({ id: "m05-s10", partId: "m05-part-4", minutes: 9, source: sources("M5-S10", ["SPEC-11.7", "SPEC-11.8", "SPEC-12.1"]), copy: sceneCopy({ eyebrow: "M5 · 11 of 11", title: "Ventricular-conduction handoff", objective: "Classify unannounced wide-QRS patterns from direct evidence.", openingTutorMessage: "I’ll remain collapsed for the independent set. If you ask for a hint, the tracing pauses and the help level is recorded.", setup: ["Use the same order every time: QRS duration → V1/V2 → lateral morphology → axis → PR/initial QRS → pacing spikes → recovery → strongest conclusion."], mechanismNarration: ["One case requires a limited conclusion rather than a forced label."], clinicalConnectionHeading: "Independent transfer", clinicalConnectionBody: "Recognition, evidence localization, and confidence are recorded separately.", transitionIntoTask: "Run the eight-step activation order on this unannounced case.", completionHeading: "Module complete", completionBody: "You can separate width from morphology, prove bundle patterns, preserve nonspecific and uncertain categories, recognize pre-excitation and pacing, and expect secondary recovery without dismissing it." }), layout: responsiveLayout("Full 12-lead and eight-step rail; Luna collapsed by default."), tutor: tutorContract({ socratic: "Which part of the activation order has not yet been supported on the waveform?", hints: ["Measure width, then compare a right-precordial lead with a lateral lead.", "If bundle anchors fail, inspect initial QRS and pacing spikes before choosing nonspecific."], tangentBridge: "Your viewport, marks, timer, and draft are frozen.", returnPrompt: "Back to case [n], at the exact lead and zoom you paused." }), caseContract: caseSpec({ selectorLessonId: "qrs-conduction", requestedConcept: "ventricular_conduction_mixed", minimumTier: "A", requiredEvidence: ["Contract-matched RBBB, LBBB, NSIVCD/limited, pre-excitation, or pacing", "QRS duration", "Paired morphology", "Initial QRS/spike evidence"], requiredLeads: ["V1", "V2", "I", "aVL", "V5", "V6", "II"], allowedUses: ["measurement", "scored_recognition", "transfer"], fallback: "authored_simulation", forbiddenClaims: ["Specific pathway beyond evidence ceiling", "Device management"] }), interactions: s10i, minimumScore: 0.82, connections: { recallFrom: "All M5 pathway models", changesNow: "Targets are unannounced and evidence is independently graded", reuseNext: "M6 tachyarrhythmias and M8/M9 recovery", clinicalUse: "A defensible wide-QRS synthesis" }, handoffs: [handoff("train", "Train · Morphology contrasts", "ventricular_conduction_mixed", "discriminate", "independent"), handoff("rapid", "Rapid · Wide-QRS recognition", "qrs_duration", "synthesize", "independent", { focus: "qrs_duration", receiptConcept: "qrs_duration", subskill: "recognize", pace: "untimed", suggestedLength: 5 })], }),
  ],
};

export default M05_VENTRICULAR_CONDUCTION_MODULE;
