export type LearningPhase = "retrieve" | "build" | "see" | "discriminate" | "do" | "explain" | "transfer" | "connect";

export type SceneChoice = {
  label: string;
  correct: boolean;
  feedback: string;
};

export type GuidedScene = {
  id: string;
  part: string;
  title: string;
  minutes: number;
  phase: LearningPhase;
  objective: string;
  lessonId: string;
  focusConcept: string;
  firstPrinciples: string[];
  clinicalBridge: string;
  recallFrom: string;
  nextConnection: string;
  task: string;
  choices: SceneChoice[];
  tutorBrief: string;
};

export type GuidedModule = {
  id: string;
  order: number;
  title: string;
  shortTitle: string;
  duration: string;
  outcome: string;
  prerequisiteIds: string[];
  prerequisiteLabel: string;
  accent: string;
  scenes: GuidedScene[];
};

const choice = (label: string, correct: boolean, feedback: string): SceneChoice => ({ label, correct, feedback });

const scene = (
  id: string,
  part: string,
  title: string,
  minutes: number,
  phase: LearningPhase,
  objective: string,
  lessonId: string,
  focusConcept: string,
  firstPrinciples: string[],
  clinicalBridge: string,
  recallFrom: string,
  nextConnection: string,
  task: string,
  choices: SceneChoice[],
  tutorBrief: string,
): GuidedScene => ({
  id,
  part,
  title,
  minutes,
  phase,
  objective,
  lessonId,
  focusConcept,
  firstPrinciples,
  clinicalBridge,
  recallFrom,
  nextConnection,
  task,
  choices,
  tutorBrief,
});

export const GUIDED_MODULES: GuidedModule[] = [
  {
    id: "leads-vectors",
    order: 2,
    title: "Leads, Vectors, Axis & the Normal 12-Lead",
    shortTitle: "Leads & vectors",
    duration: "45–60 min · 4 resumable parts",
    outcome: "Predict polarity from lead direction, estimate frontal axis, localize contiguous views, and recognize normal R-wave progression or possible lead error.",
    prerequisiteIds: ["foundations"],
    prerequisiteLabel: "Foundations: calibration, P/QRS/T, and the basic axis glance",
    accent: "#356f91",
    scenes: [
      scene("2.0", "Activate", "Why does one beat look different twelve times?", 3, "retrieve", "Reconnect the normal waveform to the 12-lead layout.", "lead-territories", "normal_ecg", ["The heart produces one evolving electrical event.", "Each lead reports that event from a different directed viewpoint."], "Localization is impossible until the viewpoint is understood.", "M1 · twelve views, one event", "Electrode-versus-lead reasoning", "Which statement is most accurate?", [choice("Each lead records a different heartbeat.", false, "The beats are shared; the viewpoints differ."), choice("A lead is a directed voltage view of the same cardiac event.", true, "Exactly. One event, multiple directed views."), choice("Only the chest leads record ventricular activity.", false, "All leads record the same cardiac electrical activity from different directions.")], "Ask the learner to predict before explaining. Keep this scene descriptive."),
      scene("2.1", "Build", "Electrodes sense; leads compare", 4, "build", "Distinguish a physical electrode from a lead direction.", "lead-territories", "normal_ecg", ["An electrode is a sensor on the body.", "A lead is a voltage comparison with a positive viewing direction.", "A wave moving toward the positive pole usually produces an upward deflection."], "Lead reversal can manufacture an apparent abnormality.", "M1 · calibration and signal quality", "Vector projection", "A depolarization wave moves directly toward a lead's positive pole. What should the main deflection do?", [choice("Become more upright", true, "Yes—the projection onto that lead is strongly positive."), choice("Become isoelectric", false, "Isoelectric is expected when the vector is near perpendicular."), choice("Always become wider", false, "Direction changes polarity/amplitude, not necessarily duration.")], "Use the viewer only to point to lead labels; use the causal model for the explanation."),
      scene("2.2", "Build", "Projection: direction becomes polarity", 5, "build", "Use a vector-to-lead projection model.", "axis", "axis_normal", ["Deflection size reflects how much of a vector lies along a lead axis.", "Parallel motion creates a large deflection; perpendicular motion approaches isoelectric."], "The same logic later explains axis, fascicular block, and reciprocal ST change.", "M1 · QRS as ventricular activation", "Limb-lead geometry", "If the net QRS vector is nearly perpendicular to a lead, what is the best prediction?", [choice("A very large positive QRS", false, "That would require the vector to point toward the lead."), choice("A nearly isoelectric QRS", true, "Correct—the positive and negative projection is small."), choice("A prolonged PR interval", false, "PR is a timing measure, not a vector projection.")], "If the learner asks for the dot product, explain it; otherwise keep the math visual."),
      scene("2.3", "See", "Limb leads and the hexaxial plane", 5, "see", "Relate I, II, III, aVR, aVL, and aVF to the frontal plane.", "axis", "axis_normal", ["The six limb leads form a set of frontal-plane directions.", "Neighboring leads view neighboring regions; opposing leads view from opposite directions."], "Frontal geometry supports axis and reciprocal-pattern reasoning.", "M1 · lead I and aVF axis glance", "Precordial/horizontal plane", "Which pair belongs to the frontal-plane axis screen taught in Foundations?", [choice("I and aVF", true, "Yes. Their QRS polarity gives the initial quadrant."), choice("V1 and V6", false, "Those are horizontal-plane anchors for ventricular morphology."), choice("V2 and V3", false, "Those are neighboring precordial leads, not the basic frontal-axis pair.")], "Highlight I and aVF only after the learner commits."),
      scene("2.4", "See", "Chest leads and the horizontal plane", 5, "see", "Understand V1–V6 as a changing anterior-to-lateral view.", "lead-territories", "r_wave_progression", ["V1–V6 traverse the horizontal plane.", "The R wave usually grows and the S wave shrinks as the viewpoint moves toward the left ventricle."], "V1/V6 later anchor bundle-branch reasoning; V1–V6 also localize anterior/lateral change.", "M1 · normal R-wave progression", "Contiguous leads and territories", "What defines the normal transition zone?", [choice("The first lead where R is taller than S", true, "Correct. It is usually around V3–V4, with normal variation."), choice("The first lead with any Q wave", false, "That is not the transition definition."), choice("The lead with the longest PR", false, "PR does not define precordial transition.")], "Never imply that imperfect progression diagnoses infarction."),
      scene("2.5", "Discriminate", "Contiguous views, territories, and opposites", 5, "discriminate", "Group anatomically related leads without assigning a diagnosis.", "lead-territories", "normal_ecg", ["Contiguous leads view adjacent regions.", "A territory is a localization hypothesis; it is not itself a disease label."], "Later ischemia reasoning depends on distribution, not a single changed lead.", "M2 · frontal and horizontal lead geometry", "Full axis refinement", "Which set is anatomically contiguous?", [choice("II, III, and aVF", true, "Yes—the inferior lead group."), choice("I, V1, and aVF", false, "These do not form one contiguous territory."), choice("aVR, V3, and V6", false, "These are separated viewpoints." )], "Answer territory tangents safely, then return to spatial reasoning."),
      scene("2.6", "Do", "Axis: quadrant first, lead II second", 6, "do", "Classify and refine frontal QRS axis.", "axis", "axis_normal", ["I and aVF establish the first quadrant.", "When I is positive and aVF negative, lead II helps separate normal-leftward from definite left-axis deviation.", "Degrees and machine values refine—not replace—the tracing."], "Axis becomes causal evidence for fascicular block and chamber forces.", "M1 · coarse I/aVF rule", "R-wave progression and placement", "Lead I is positive, aVF negative, and lead II positive. What is the strongest beginner conclusion?", [choice("Definitely right-axis deviation", false, "Lead I positivity argues against a rightward quadrant."), choice("A leftward but still potentially normal axis", true, "Correct. Lead II positivity supports the normal extension toward −30°."), choice("Complete heart block", false, "Axis polarity does not establish AV block." )], "Use grounded axis evidence but do not invent a degree when none is supplied."),
      scene("2.7", "Transfer", "Normal variation or lead-placement problem?", 6, "transfer", "Integrate axis, progression, and acquisition quality on a new ECG.", "lead-territories", "r_wave_progression", ["Rotation, body habitus, electrode placement, and normal variation change morphology.", "Before naming pathology, check whether the pattern is internally plausible and new."], "A prior tracing and correct lead placement can prevent unnecessary escalation.", "M1 · readable for what?; M2 · geometry", "M3 · rhythm analysis on trustworthy leads", "Poor R-wave progression appears in isolation. What is the best next reasoning step?", [choice("Call anterior infarction immediately", false, "Progression alone is not specific enough."), choice("Check lead placement, context, and a prior ECG before assigning cause", true, "Exactly—describe the finding and test plausible alternatives."), choice("Ignore all precordial leads", false, "The leads remain useful; the pattern needs verification." )], "Close with a one-line synthesis and offer a lead/axis Train handoff."),
    ],
  },
  {
    id: "rhythm-ectopy",
    order: 3,
    title: "Rate, Sinus Rhythm, Pauses & Ectopy",
    shortTitle: "Rhythm & ectopy",
    duration: "45–55 min · 4 resumable parts",
    outcome: "Use rate, regularity, atrial activity, P–QRS relationships, and timing to distinguish sinus variants, premature beats, escape beats, pauses, and artifact.",
    prerequisiteIds: ["foundations"],
    prerequisiteLabel: "Foundations: box timing, lead-II rhythm, P/QRS relationships",
    accent: "#7c5f9b",
    scenes: [
      scene("3.0", "Activate", "Build the rhythm ladder", 3, "retrieve", "Order the questions that make rhythm interpretation reproducible.", "rhythm-basics", "sinus_rhythm", ["Start with rate and R–R regularity.", "Then seek atrial activity, relate P waves to QRS complexes, and inspect QRS width."], "A structured ladder prevents a fast rhythm from becoming a reflex label.", "M1 · rate and sinus criteria", "Rate under irregular conditions", "What should come before naming a rhythm?", [choice("Check rate, regularity, atrial activity, P–QRS relation, and QRS width", true, "That sequence builds an evidence-based rhythm description."), choice("Choose the closest memorized picture", false, "Pattern memory helps only after the basic evidence is checked."), choice("Read the machine diagnosis first", false, "The machine can be compared after your own evidence check." )], "Let a fluent learner test out with a novel strip."),
      scene("3.1", "Do", "Rate when the rhythm is not tidy", 5, "do", "Choose and apply a rate method appropriate to regularity.", "rate", "rate", ["The 300 rule assumes a regular rhythm.", "A longer time sample is better for irregular rhythms; estimates should state their method and tolerance."], "A wrong numeric rate can change apparent urgency, so grading must compare with grounded heart rate.", "M1 · regularity before rate", "Sinus source versus sinus rate", "An irregular rhythm spans a calibrated six-second strip. Which method fits best?", [choice("Count QRS complexes and multiply by ten", true, "Correct—this estimates the average ventricular rate over six seconds."), choice("Use 300 divided by one R–R interval", false, "One interval is not representative when the rhythm is irregular."), choice("Count P waves only", false, "The requested ventricular rate is anchored to QRS complexes." )], "If the learner provides a number, compare it to the packet value rather than rewarding any integer."),
      scene("3.2", "Build", "Sinus is an origin, not a speed", 5, "build", "Separate sinus mechanism from bradycardia or tachycardia.", "rhythm-basics", "sinus_rhythm", ["A sinus rhythm can be slow, normal-rate, or fast.", "Consistent P morphology and a stable P–QRS relationship support a common atrial source."], "Clinical context explains why sinus rate changed; the ECG describes the mechanism and rate.", "M1 · sinus checklist", "Prematurity and ectopic origin", "A tracing has upright, same-shaped P waves before every QRS but a rate of 48. What is the best description?", [choice("Not sinus because it is below 60", false, "Rate is not part of the sinus-source definition."), choice("Sinus bradycardia pattern", true, "Correct—sinus source with a slow rate."), choice("Atrial fibrillation", false, "Organized consistent P waves argue against AF." )], "Acknowledge correct-but-ahead clinical questions and park them as a breadcrumb."),
      scene("3.3", "Build", "Early impulse, different route", 5, "build", "Predict how timing and origin change a beat.", "ectopy", "premature_ventricular_complex", ["Premature means earlier than the expected sinus timing.", "A ventricular origin usually activates myocardium cell-to-cell, producing a wider, different QRS."], "The timing–P wave–QRS width triad is safer than a single-feature shortcut.", "M2 · vector direction; M3 · sinus timing", "PAC versus PVC", "Which feature is necessary before calling a beat premature?", [choice("It occurs earlier than the expected rhythm", true, "Exactly. Morphology alone does not define prematurity."), choice("It has a tall T wave", false, "T-wave height does not establish early timing."), choice("It is followed by exactly two seconds of pause", false, "Pause length varies and is not the definition." )], "Use a causal animation before showing labels."),
      scene("3.4", "Discriminate", "PAC, PVC, aberrancy, or pacing?", 6, "discriminate", "Use atrial activity, QRS width, and pause timing to compare premature beats.", "ectopy", "premature_atrial_complex", ["A premature atrial P may hide in the preceding T wave.", "A PAC can conduct aberrantly; a wide premature beat is not automatically ventricular.", "A pacing spike is a separate clue."], "Close mimics matter because ectopy labels should follow visible evidence, not width alone.", "M3 · origin and prematurity", "Pauses and escape", "A wide early beat has a subtle premature P wave deforming the prior T. What alternative deserves consideration?", [choice("PAC with aberrant conduction", true, "Yes—the atrial clue keeps PAC with aberrancy in the differential."), choice("Complete AV block", false, "One early conducted beat does not establish AV dissociation."), choice("Normal sinus beat", false, "Its early timing and altered morphology need explanation." )], "Require the learner to click the decisive evidence before revealing the label."),
      scene("3.5", "Build", "Pauses, reset, and escape", 5, "build", "Distinguish early ectopy from late rescue beats and unfilled pauses.", "ectopy", "premature_ventricular_complex", ["An escape beat arrives late because a lower pacemaker rescues a pause.", "A premature beat arrives early and may reset the sinus clock.", "Artifact can create a false gap while the real rhythm marches through."], "Syncope reasoning later depends on whether impulses were early, blocked, absent, or rescued.", "M3 · expected sinus timing", "Patterned ectopy", "A beat occurs after a longer-than-expected pause, not before the next expected sinus beat. Which timing label fits?", [choice("Premature", false, "Premature beats occur early."), choice("Escape", true, "Correct—a late rescue beat is an escape beat."), choice("Tachycardia", false, "One late beat does not define a fast rhythm." )], "Use independent atrial and ventricular rulers; do not over-specify the escape focus without evidence."),
      scene("3.6", "See", "Patterns are not burden", 4, "see", "Describe bigeminy, trigeminy, and couplets without extrapolating a 10-second sample.", "ectopy", "premature_ventricular_complex", ["Pattern names describe sequence.", "A short ECG cannot establish a day-long ectopic burden."], "Pattern and symptoms can prompt further monitoring, but the tracing alone does not quantify long-term burden.", "M3 · PAC/PVC timing", "Artifact and mixed discrimination", "Every normal beat is followed by a PVC. Which descriptor fits the observed sequence?", [choice("Ventricular bigeminy", true, "Correct—alternating normal and ventricular premature beats."), choice("Third-degree AV block", false, "The repeating early ventricular beats do not show AV dissociation."), choice("A 50% daily PVC burden", false, "A ten-second strip cannot establish daily burden." )], "Surface the observation window whenever the learner makes a burden claim."),
      scene("3.7", "Transfer", "Rhythm under noise and uncertainty", 6, "transfer", "Integrate the ladder across sinus variation, ectopy, escape, and artifact.", "rhythm-basics", "sinus_rhythm", ["Underlying QRS complexes may march through artifact.", "The best answer can be a descriptive rhythm plus an explicit uncertainty."], "In real practice, repeating a poor-quality tracing can be the most important next step.", "M1 · readable for what?; M3 · full rhythm ladder", "M4 · conducted and dropped atrial impulses", "The baseline is chaotic, but narrow QRS complexes march regularly and P waves are intermittently visible. What is safest?", [choice("Definite atrial fibrillation", false, "Regular marching QRS complexes and visible P waves argue for caution."), choice("Likely artifact over an organized rhythm; improve signal before a specific label", true, "Exactly—describe what remains reliable and repeat/repair the signal."), choice("Ventricular fibrillation", false, "Organized recurring QRS complexes are visible." )], "Close with a Train handoff containing recognition, timing, and evidence subskills separately."),
    ],
  },
  {
    id: "av-brady",
    order: 4,
    title: "AV Conduction & Bradyarrhythmias",
    shortTitle: "AV conduction",
    duration: "50–65 min · 4 resumable parts",
    outcome: "Measure PR, distinguish defensible AV-conduction patterns, identify AV dissociation and escape, and connect bradycardia to perfusion and reversible causes.",
    prerequisiteIds: ["foundations", "rhythm-ectopy"],
    prerequisiteLabel: "Foundations PR boundaries + M3 P–QRS timing",
    accent: "#9b633e",
    scenes: [
      scene("4.0", "Activate", "Are atrial impulses reaching the ventricles?", 3, "retrieve", "March P waves and QRS complexes independently.", "pr-av-block", "av_block_first_degree", ["A slow ventricular rate does not reveal where the delay occurred.", "The P–QRS relationship is the starting evidence."], "Dropped, delayed, dissociated, and absent impulses have different implications.", "M3 · pause versus ectopy", "AV node versus His–Purkinje", "What should be marched separately when AV block is suspected?", [choice("P waves and QRS complexes", true, "Correct—compare atrial and ventricular timing."), choice("ST segments and T waves", false, "Those assess repolarization, not AV conduction timing."), choice("Only the machine rate", false, "A rate cannot show the conduction relationship." )], "Do not reveal the block type until the learner demonstrates the relationship."),
      scene("4.1", "Build", "AV-node delay versus distal failure", 5, "build", "Relate conduction level to timing and QRS clues without false certainty.", "pr-av-block", "av_block_first_degree", ["The AV node normally delays conduction.", "The His–Purkinje system distributes activation rapidly.", "Surface ECG clues can suggest but not always prove the level of block."], "Infranodal concern and symptoms change escalation, but ECG morphology is not the whole patient.", "M1 · PR and QRS physiology", "PR measurement across beats", "Which statement is most defensible?", [choice("Every wide QRS proves infranodal AV block", false, "Wide QRS is a clue, not proof of the block level."), choice("PR behavior and QRS morphology together help localize, but uncertainty can remain", true, "Exactly."), choice("The AV node creates the QRS complex", false, "The QRS reflects ventricular activation." )], "Use cautious causal language and invite an advanced tangent without abandoning the task."),
      scene("4.2", "Do", "Measure PR, then ask how it changes", 5, "do", "Measure PR over multiple beats and classify its behavior.", "pr-av-block", "av_block_first_degree", ["One PR interval is insufficient when the question is progression or constancy.", "Mark P onset and QRS onset consistently in the same clear lead."], "A borderline machine value should be verified on the tracing.", "M1 · PR boundaries", "First-degree and Wenckebach", "Three conducted PR intervals measure 220, 220, and 220 ms. Which description fits?", [choice("Prolonged and constant", true, "Correct—describe the measurable pattern before assigning cause."), choice("Progressively lengthening", false, "The values are unchanged."), choice("AV dissociation", false, "A stable P–QRS relationship is present." )], "Prompt a click on boundaries before exposing calipers."),
      scene("4.3", "See", "Long but all conducted: first-degree pattern", 4, "see", "Recognize prolonged constant PR with 1:1 conduction.", "pr-av-block", "av_block_first_degree", ["Every P conducts to a QRS.", "The PR is longer than the reference and remains constant."], "This is a conduction finding; whether it explains symptoms requires context.", "M4 · multi-beat PR measurement", "Progressive and dropped conduction", "Which feature excludes second-degree block on this strip?", [choice("Every P wave is followed by a QRS", true, "Yes—there are no nonconducted P waves here."), choice("The heart rate is below 100", false, "Rate does not exclude second-degree block."), choice("Lead II is upright", false, "Lead orientation does not answer whether beats are dropped." )], "Credit a correct ahead label, then return to the evidence chain."),
      scene("4.4", "Build", "Progressive delay: Wenckebach", 6, "build", "Explain grouped beating and progressive PR behavior before a dropped QRS.", "pr-av-block", "av_block_second_degree_mobitz_i", ["The AV node delays more across a cycle until one atrial impulse fails to conduct.", "The pattern then resets."], "Corpus scarcity means the causal animation can teach acquisition, but real-case mastery remains data-gated.", "M4 · constant PR", "Mobitz II and 2:1 uncertainty", "PR intervals progressively lengthen before one P is not followed by QRS. Which pattern is supported?", [choice("Mobitz I / Wenckebach", true, "Correct—the progressive sequence is the discriminator."), choice("First-degree AV block", false, "First-degree has 1:1 conduction without a dropped QRS."), choice("Atrial fibrillation", false, "Organized P waves with a repeating conduction pattern are visible." )], "Clearly label authored animation versus real recording."),
      scene("4.5", "Discriminate", "Mobitz II, blocked PAC, or 2:1 block?", 6, "discriminate", "Use constancy, atrial timing, and uncertainty to avoid over-subtyping.", "pr-av-block", "av_block_second_degree_mobitz_ii", ["Mobitz II has unexpectedly nonconducted P waves with constant conducted PR intervals.", "A blocked premature P may deform the preceding T.", "With 2:1 conduction, progression may be unobservable."], "A cautious `2:1 AV block; level uncertain` can be better than a forced subtype.", "M3 · hidden PAC and pause timing", "Complete AV dissociation", "Every other P wave is blocked, so only one PR interval repeats. What is the best label?", [choice("Definite Mobitz I", false, "Progression cannot be seen with a single conducted PR per cycle."), choice("Definite Mobitz II", false, "The same limitation prevents certainty."), choice("2:1 AV block; subtype not established on this strip", true, "Exactly—state what the tracing supports." )], "Reward uncertainty when the required discriminator is absent."),
      scene("4.6", "Build", "Two clocks: complete AV block", 6, "build", "Demonstrate independent atrial and ventricular rhythms.", "pr-av-block", "av_block_third_degree", ["P waves and QRS complexes each march regularly but without a stable relationship.", "The escape focus influences rate and QRS morphology."], "Symptoms and perfusion matter immediately; the ECG establishes the conduction pattern, not the entire cause.", "M3 · escape timing", "Bradycardia context and action", "Which evidence most strongly supports complete AV block?", [choice("A long PR on one beat", false, "One long PR does not show dissociation."), choice("P waves and QRS complexes march independently across multiple beats", true, "Correct—that is AV dissociation."), choice("A heart rate of 58 alone", false, "Rate alone is nonspecific." )], "Use two visible rulers and require several beats before confirmation."),
      scene("4.7", "Transfer", "Bradycardia: tracing, perfusion, cause", 7, "transfer", "Connect a grounded rhythm description to symptom/perfusion assessment and next-step category.", "pr-av-block", "av_block_third_degree", ["The 2025 AHA bradycardia pathway begins with clinical compromise, support, and a 12-lead when feasible.", "Drugs, ischemia, hypoxia, and electrolytes are hypotheses requiring context."], "A precise rhythm label must not delay recognizing hypotension, shock, ischemic discomfort, altered mental status, or acute heart failure.", "M4 · AV patterns", "M5 · combined conduction and pacing", "A patient with bradycardia is hypotensive and confused. What takes priority?", [choice("Finish a highly specific block subtype before acting", false, "Clinical compromise takes priority while rhythm assessment continues."), choice("Recognize compromise, support the patient, and follow the reviewed bradycardia escalation pathway", true, "Correct—the ECG and clinical state are integrated."), choice("Assume the ECG alone identifies the cause", false, "Reversible causes require clinical data." )], "Clinical actions are versioned content; keep the tutor within the reviewed action categories."),
    ],
  },
  {
    id: "ventricular-conduction",
    order: 5,
    title: "Ventricular Activation, Conduction, Pre-excitation & Pacing",
    shortTitle: "Ventricular conduction",
    duration: "50–65 min · 4 resumable parts",
    outcome: "Reason from QRS width and morphology through bundle/fascicular delay, pre-excitation, pacing, and expected secondary ST–T change.",
    prerequisiteIds: ["leads-vectors", "av-brady"],
    prerequisiteLabel: "M2 vectors/axis + M4 AV sequence and QRS boundaries",
    accent: "#4d7f58",
    scenes: [
      scene("5.0", "Activate", "Width is not morphology", 3, "retrieve", "Separate QRS duration from activation pattern.", "qrs-conduction", "qrs_duration", ["Duration asks how long ventricular activation took.", "Morphology asks how the activation traveled."], "A wide QRS changes the differential and also changes how ST–T is interpreted.", "M1 · QRS boundaries; M2 · vectors", "Bundle activation model", "Two QRS complexes are both 150 ms but have different shapes. What follows?", [choice("They must have the same cause", false, "Equal duration does not imply equal activation route."), choice("Their duration matches, but morphology still needs separate analysis", true, "Exactly."), choice("Both prove ventricular tachycardia", false, "A wide QRS in a resting ECG has many causes." )], "Do not let a neutral QRS click masquerade as conduction mastery."),
      scene("5.1", "Build", "Block a bundle; predict the terminal force", 6, "build", "Use delayed ventricular activation to predict V1/V6 morphology.", "bundle-branch-blocks", "right_bundle_branch_block", ["Normal ventricles activate rapidly through both bundles.", "When one side is delayed, the terminal QRS vector points toward the ventricle activated last."], "This mechanism is more transferable than a mnemonic alone.", "M2 · vector projection and V1/V6", "RBBB", "If the right ventricle activates last, where should the terminal force point?", [choice("Rightward/anterior, often toward V1", true, "Correct—that terminal direction helps explain RBBB morphology."), choice("Only toward aVL", false, "The key delayed force is rightward/anterior."), choice("It changes only the PR interval", false, "Bundle delay changes ventricular activation and QRS." )], "Animate first, then anchor the same prediction on a real trace."),
      scene("5.2", "Discriminate", "RBBB and its near-mimics", 6, "discriminate", "Combine V1 and lateral-lead morphology with duration.", "bundle-branch-blocks", "right_bundle_branch_block", ["RBBB patterns often show terminal positivity in V1 and a broad terminal S in lateral leads.", "Incomplete RBBB and normal rSr′ variants require width and context.", "RVH and pacing can mimic parts of the pattern."], "Syncope with conduction disease is a different context from an incidental stable RBBB.", "M5 · delayed-right activation", "LBBB", "Why is V1 alone insufficient for a complete RBBB call?", [choice("RBBB can be diagnosed from rate alone", false, "Rate is not the defining evidence."), choice("Duration and a compatible lateral-lead terminal S pattern also matter", true, "Correct—use paired evidence."), choice("V1 never contains useful conduction information", false, "V1 is an important anchor, just not sufficient alone." )], "Show a target, normal rSr′, and RVH/paced mimic before transfer."),
      scene("5.3", "Build", "LBBB and secondary repolarization", 6, "build", "Explain delayed LV activation and expected ST–T discordance.", "bundle-branch-blocks", "left_bundle_branch_block", ["Delayed LV activation produces a broad lateral R pattern and a predominantly negative early precordial QRS.", "Repolarization follows the altered activation, creating secondary ST–T changes."], "LBBB complicates ischemia interpretation; expected secondary change is taught before acute criteria.", "M5 · terminal-force model", "Fascicular/axis change", "In uncomplicated LBBB, why can ST–T point opposite the main QRS?", [choice("Altered activation also alters the recovery sequence", true, "Exactly—secondary repolarization follows abnormal depolarization."), choice("Every discordant T wave proves acute infarction", false, "Discordance can be expected in LBBB."), choice("The atria activate backward", false, "The explanation concerns ventricular activation/recovery." )], "Answer ischemia tangents conditionally and park detailed criteria for M8."),
      scene("5.4", "Build", "Fascicles redirect the axis", 6, "build", "Use axis as causal evidence for fascicular delay.", "fascicular-preexcitation", "left_anterior_fascicular_block", ["A fascicular block changes which LV region activates first and redirects the net frontal vector.", "Axis pattern must be interpreted after excluding alternatives."], "This is why axis had to precede fascicular diagnosis.", "M2 · full axis refinement", "Combined conduction", "A proposed LAFB has a normal frontal axis. What is missing?", [choice("Nothing; axis is unrelated", false, "Axis shift is central to the fascicular pattern."), choice("The expected leftward axis evidence", true, "Correct—the label is not supported without its vector consequence."), choice("A prolonged QT", false, "QT is not the defining fascicular criterion." )], "Use the learner's axis estimate from the viewer state rather than ignoring it."),
      scene("5.5", "Discriminate", "Pre-excitation: two routes fuse", 6, "discriminate", "Relate short PR and delta wave to accessory-pathway timing.", "fascicular-preexcitation", "wolff_parkinson_white", ["An accessory pathway can begin ventricular activation before the normal AV/His–Purkinje route arrives.", "The fused onset creates a delta wave and can widen the QRS."], "Pre-excitation changes tachycardia differential and AV-nodal medication safety, addressed in reviewed clinical cases.", "M4 · AV delay; M5 · QRS morphology", "Pacing", "Which feature set best supports pre-excitation?", [choice("Short PR, delta-wave onset, and a fused/wider QRS", true, "Correct—the features follow from two activation routes."), choice("Long PR and narrow QRS only", false, "That does not describe pre-excitation."), choice("Irregularly irregular rhythm alone", false, "Rhythm irregularity is not the defining pattern." )], "Do not claim WPW from an isolated short PR without a delta wave."),
      scene("5.6", "Do", "Pacing: spike, capture, sensing", 6, "do", "Inspect pacing timing and response as separate questions.", "paced", "paced_rhythm", ["A pacing artifact should precede the chamber response it triggers.", "Capture and sensing are distinct; paced ventricular activation alters QRS/ST–T."], "The current 100 Hz derivative may miss narrow spikes, so scored spike detection is data-gated.", "M4 · atrial/ventricular timing", "Chamber/voltage clues", "A visible pacing spike is not followed by a QRS. Which observation is supported?", [choice("Possible failure to capture", true, "Yes—provided the spike and missing response are reliably recorded."), choice("Normal ventricular capture", false, "Capture requires a following ventricular response."), choice("Definite acute MI", false, "The pacing observation does not establish infarction." )], "Disclose sampling limits; use authored simulation for the causal task and do not award real-case spike mastery at 100 Hz."),
      scene("5.8", "Transfer", "Morphology without an announced target", 7, "transfer", "Integrate RBBB, LBBB, IVCD, pacing, pre-excitation, voltage, and normal variants.", "bundle-branch-blocks", "qrs_duration", ["A defensible read reports width, morphology, lead evidence, secondary change, and uncertainty.", "Close mimics are deliberately interleaved."], "The output prepares the learner for wide-complex tachycardia and repolarization interpretation.", "M2/M4/M5 · vectors, timing, morphology", "M6 · tachyarrhythmia reasoning", "The QRS is wide but does not meet full RBBB or LBBB morphology. Which label is strongest?", [choice("Nonspecific intraventricular conduction delay, with morphology described", true, "Correct—do not force a bundle label."), choice("Definite RBBB because it is wide", false, "Width alone is insufficient."), choice("Normal QRS", false, "The grounded duration is wide." )], "Offer target–mimic–normal Train and preserve the exact return waypoint."),
    ],
  },
  {
    id: "tachyarrhythmias",
    order: 6,
    title: "Tachyarrhythmias: Narrow, Wide, Regular & Irregular",
    shortTitle: "Tachyarrhythmias",
    duration: "60–75 min · 4 resumable parts",
    outcome: "Use stability, regularity, QRS width, atrial activity, and AV relationship to reason through common tachyarrhythmias and safe action categories.",
    prerequisiteIds: ["rhythm-ectopy", "ventricular-conduction"],
    prerequisiteLabel: "M3 rhythm ladder + M5 QRS morphology",
    accent: "#a0445b",
    scenes: [
      scene("6.0", "Activate", "Stable enough to reason, unstable enough to act", 4, "retrieve", "Prioritize perfusion assessment before elegant subtype analysis.", "svt", "supraventricular_tachycardia", ["A rhythm strip cannot tell whether the patient is hypotensive, shocked, ischemic, confused, or in acute heart failure.", "Clinical compromise changes the immediate path."], "The same ECG can have a different priority in a different patient context.", "M3 · rate/rhythm; M4 · perfusion context", "Tachycardia matrix", "What information cannot be inferred from the ECG alone?", [choice("QRS width", false, "QRS width is visible/measurable on the ECG."), choice("Blood pressure and signs of shock", true, "Correct—those require clinical assessment."), choice("R–R regularity", false, "Regularity is visible on the trace." )], "Do not let the tutor supply hidden vital signs before the learner asks or commits."),
      scene("6.1", "Build", "Automaticity, triggered activity, and reentry", 5, "build", "Connect mechanism to onset and regularity without over-subtyping.", "svt", "supraventricular_tachycardia", ["Automatic rhythms often warm up/cool down; reentry can start and stop abruptly.", "A static ten-second ECG may not contain onset, so do not claim it saw onset."], "Mechanism guides questions and response patterns but must remain evidence-bound.", "M3 · ectopic focus", "Regularity × width", "A static resting ECG shows a regular narrow tachycardia but no onset. What can be said?", [choice("Abrupt onset is proven", false, "Onset was not recorded."), choice("Regular narrow-complex tachycardia; mechanism needs more evidence", true, "Exactly—describe what is present."), choice("Sinus tachycardia is excluded by rate alone", false, "Rate alone does not exclude sinus origin." )], "Explicitly distinguish general teaching from evidence on this case."),
      scene("6.2", "Do", "The 2×2 tachycardia matrix", 5, "do", "Classify regular/irregular and narrow/wide before naming a rhythm.", "svt", "supraventricular_tachycardia", ["Regularity and QRS width reduce the candidate set.", "Atrial activity and AV relationship refine it."], "This fast scaffold supports safe rapid recognition without becoming a typing test.", "M3 · regularity; M5 · QRS width", "Narrow regular rhythms", "An irregular wide-complex tachycardia belongs where?", [choice("Irregular + wide", true, "Correct—now consider AF with aberrancy/pre-excitation, polymorphic VT, and artifact as appropriate."), choice("Regular + narrow", false, "Both observed dimensions conflict."), choice("Rate cannot be organized", false, "The matrix describes morphology and regularity, not exact mechanism." )], "In timed mode, ask only for quadrant + priority, then debrief fully."),
      scene("6.3", "Discriminate", "Sinus tachycardia, atrial tachycardia, or SVT?", 6, "discriminate", "Use P morphology, AV relation, context, and recorded onset when available.", "svt", "supraventricular_tachycardia", ["A regular narrow tachycardia is a description, not automatically AVNRT.", "P waves may be hidden or retrograde; exact subtype can remain uncertain."], "Treat the underlying context of sinus tachycardia; do not suppress a compensatory rhythm based on label alone.", "M3 · sinus source", "Flutter", "P waves are not clearly visible in a very regular narrow tachycardia. What is safest?", [choice("Definite sinus tachycardia", false, "Sinus P-wave evidence is missing."), choice("Regular narrow-complex tachycardia; SVT is a working category", true, "Correct—retain uncertainty about mechanism."), choice("Definite ventricular fibrillation", false, "Organized narrow QRS complexes are present." )], "Accept a broader correct category when subtype evidence is absent."),
      scene("6.4", "Build", "Flutter waves can hide behind a 2:1 response", 6, "build", "Relate atrial circuit rate to AV conduction ratios.", "af-flutter", "atrial_flutter", ["Atrial flutter can conduct 2:1, variably, or with other ratios.", "A regular ventricular response near 150 is a clue, not a standalone diagnosis."], "Rate and rhythm management depend on stability and patient factors, not one mnemonic.", "M4 · AV conduction ratios", "Atrial fibrillation", "A regular narrow tachycardia near 150 has subtle repetitive atrial activity. What should you inspect next?", [choice("Inferior leads and V1 for organized flutter activity", true, "Yes—seek atrial evidence and conduction ratio."), choice("Only the QT interval", false, "QT does not answer the atrial mechanism."), choice("Assume AF because it is fast", false, "AF is typically irregularly irregular." )], "Highlight atrial activity only if a visible validated ROI exists."),
      scene("6.5", "Discriminate", "AF, variable flutter, ectopy, or artifact", 6, "discriminate", "Use organized P activity and R–R behavior to compare irregular rhythms.", "af-flutter", "atrial_fibrillation", ["AF has no consistent organized P waves and an irregularly irregular ventricular response.", "Frequent PACs and artifact can create irregularity while organized atrial activity persists."], "The ECG establishes a rhythm pattern; stroke risk and management require a clinical framework.", "M3 · PAC/artifact", "Wide-complex tachycardia", "Which combination best supports AF?", [choice("No consistent P waves plus irregularly irregular R–R intervals", true, "Correct—both atrial and ventricular evidence align."), choice("Sawtooth atrial waves with fixed 2:1 conduction", false, "That supports flutter."), choice("One premature wide beat", false, "That is ectopy, not sustained AF." )], "A management tangent should be conditional, not a case-specific prescription."),
      scene("6.6", "Build", "Wide-complex tachycardia: uncertainty is a safety finding", 7, "build", "Build a VT-versus-SVT-with-aberrancy differential from morphology and AV evidence.", "bundle-branch-blocks", "wide_complex_tachycardia", ["A wide regular tachycardia can be ventricular or supraventricular with abnormal conduction/pre-excitation.", "AV dissociation, capture/fusion, extreme axis, baseline comparison, and morphology contribute; none should be invented."], "In an appropriate clinical context, unresolved WCT deserves a safety-first approach and expert help.", "M5 · BBB/pre-excitation/pacing", "Polymorphic rhythms and QT", "Which boundary applies to the installed expert-labelled WCT lane?", [choice("Award full ACLS mastery from a ten-second rhythm window", false, "A labelled rhythm window does not provide pulse, perfusion, treatment response, or an action algorithm."), choice("Use it for focused rhythm recognition while keeping management and ACLS locked", true, "Correct—the expert label supports the rhythm target only."), choice("Relabel resting bundle-branch block as WCT", false, "That would be clinically wrong." )], "Use expert rhythm windows only for their audited target; never invent hemodynamics, management, or ACLS evidence."),
      scene("6.7", "Transfer", "Tachycardia under the right clock", 7, "transfer", "Separate a rapid priority response from a complete untimed interpretation.", "af-flutter", "atrial_fibrillation", ["A 20-second task should ask for one dominant rhythm/priority, not six typed fields.", "The full explanation follows after commitment."], "The 2025 AHA tachycardia pathway separates instability, QRS width, regularity, and action categories.", "M6 · matrix and stability", "M7 · QT and torsades", "A patient has a regular monomorphic wide tachycardia but is currently stable. Which initial category is appropriate?", [choice("Wide-QRS tachycardia requiring a safety-focused differential and reviewed pathway", true, "Correct—do not force an unsupported mechanism."), choice("Normal sinus rhythm", false, "The rhythm is fast and wide."), choice("Give a patient-specific drug recommendation from the ECG alone", false, "Management requires full clinical context and a reviewed protocol." )], "Offer separate scores for recognition, priority, evidence, and confidence."),
    ],
  },
  {
    id: "chambers-voltage",
    order: 7,
    title: "Chambers, Voltage & R-Wave Progression",
    shortTitle: "Chambers & voltage",
    duration: "40–55 min · 4 resumable parts",
    outcome: "Use atrial morphology, QRS voltage, axis, precordial balance, and R-wave progression as evidence—while recognizing placement, body habitus, age, and normal-variant limits.",
    prerequisiteIds: ["leads-vectors", "ventricular-conduction"],
    prerequisiteLabel: "M2 lead geometry/axis + M5 ventricular activation and secondary ST–T change",
    accent: "#8b6b35",
    scenes: [
      scene("7.0", "Activate", "A large signal is not the same as a large chamber", 3, "retrieve", "Reconnect vector projection, distance, and lead placement to voltage.", "hypertrophy", "left_ventricular_hypertrophy", ["Recorded voltage reflects electrical force projected onto a lead.", "Muscle mass matters, but so do direction, distance, body habitus, age, and placement."], "ECG chamber criteria are clues that may justify correlation; they are not an echocardiogram.", "M2 · vector projection and placement", "Atrial morphology", "A tall QRS meets one voltage criterion in a young athlete. What is the strongest first statement?", [choice("The voltage criterion is present, but isolated voltage may be a normal variant", true, "Correct—name the evidence and its limitation."), choice("Anatomical LVH is proven", false, "One ECG voltage criterion cannot prove anatomy."), choice("Acute infarction is proven", false, "Voltage alone does not establish infarction.")], "Begin with the learner's causal explanation; do not lead with a memorized threshold."),
      scene("7.1", "See", "Atrial enlargement: read the P wave in more than one view", 5, "see", "Use P-wave duration and morphology as chamber clues.", "hypertrophy", "atrial_enlargement", ["Atrial depolarization has right- and left-atrial components.", "Lead II emphasizes duration and contour; V1 can separate early positive and later negative components."], "A P-wave pattern can support an enlargement hypothesis, but rhythm, placement, and imaging context still matter.", "M1/M3 · P-wave boundaries and sinus evidence", "LVH voltage and axis", "Why is a single tall P wave in one noisy lead insufficient?", [choice("Morphology should be reproducible and interpreted with duration, other leads, and signal quality", true, "Exactly—one noisy amplitude is weak evidence."), choice("Atrial size is never related to P waves", false, "P morphology can provide a clue."), choice("Only the QRS can be measured", false, "P-wave duration and morphology are measurable when clear.")], "Use paired lead-II/V1 views and accept not-assessable when P boundaries are unclear."),
      scene("7.2", "Do", "LVH: apply a criterion, then test its credibility", 6, "do", "Measure an LVH voltage criterion and weigh corroborating evidence.", "hypertrophy", "left_ventricular_hypertrophy", ["LV mass can increase electrical force, raising voltage in selected leads.", "Axis, lateral repolarization, age, body habitus, and clinical context change how persuasive the criterion is."], "The useful read is criterion + corroboration + limitation—not a binary anatomy claim.", "M2 · lead direction; M5 · secondary repolarization", "RVH", "What should follow a measured LVH voltage criterion?", [choice("Seek corroborating morphology/context and state that ECG criteria are imperfect", true, "Correct—measurement starts the reasoning; it does not finish it."), choice("Stop because the diagnosis is certain", false, "Voltage criteria have important false positives and negatives."), choice("Ignore calibration", false, "Voltage measurement is meaningless without calibration.")], "Require the learner to identify the measured leads and preserve the calibration state."),
      scene("7.3", "Discriminate", "RVH: combine rightward forces, not one tall R", 6, "discriminate", "Integrate axis and precordial balance when considering RVH.", "hypertrophy", "right_ventricular_hypertrophy", ["Greater right-ventricular force can shift the frontal vector rightward and increase anterior/rightward forces in V1.", "Normal variants, RBBB, posterior infarction, lead placement, and age can mimic one feature."], "A multi-feature pattern deserves more weight than a solitary V1 measurement.", "M2 · axis and V1–V6; M5 · RBBB", "R-wave progression", "A tall R in V1 appears with RBBB morphology. What is safest?", [choice("Explain the V1 finding in the conduction context before assigning RVH", true, "Correct—RBBB is a competing mechanism."), choice("Call RVH from V1 alone", false, "One feature is not enough."), choice("Call the ECG normal without review", false, "The morphology still requires description.")], "Build a target–mimic comparison with RBBB and normal variants before scoring recognition."),
      scene("7.4", "Build", "R-wave progression is a sequence, not a single lead", 5, "build", "Identify the precordial transition zone and normal variation.", "lead-territories", "r_wave_progression", ["V1–V6 rotate the viewpoint from right/anterior toward left/lateral.", "The R wave usually grows as the S wave shrinks; transition is where R becomes larger than S."], "Normal transition varies, so describe the sequence before judging it abnormal.", "M1/M2 · normal transition and horizontal plane", "Poor progression differential", "Which observation defines transition?", [choice("The first precordial lead where R exceeds S", true, "Correct—name the lead and acknowledge normal variation."), choice("The first lead with any positive deflection", false, "That does not define transition."), choice("The lead with the longest PR", false, "PR is unrelated to precordial transition.")], "Use a V1→V6 scrub with a keyboard/tap alternative; the learner must mark the transition lead."),
      scene("7.5", "Discriminate", "Poor progression: describe first, then investigate", 6, "discriminate", "Differentiate placement, rotation/body habitus, conduction, chamber forces, and prior infarction hypotheses.", "lead-territories", "r_wave_progression", ["Poor R-wave progression is a descriptive pattern with multiple causes.", "Lead placement and prior comparison should be checked before attributing it to infarction."], "This discipline prevents a common machine-read and learner overcall.", "M2 · placement; M5 · conduction; M7 · chamber forces", "Strain patterns", "Poor progression is isolated and V1/V2 placement is uncertain. What comes next?", [choice("Verify placement and compare a prior before assigning cause", true, "Exactly—acquisition and change over time are decisive checks."), choice("Definite anterior infarction", false, "The pattern is not specific enough."), choice("Discard every precordial finding", false, "Describe what remains assessable and repeat correctly.")], "Do not award target recognition if the active corpus lacks lead-level progression evidence."),
      scene("7.6", "Build", "Strain is a secondary repolarization pattern", 6, "build", "Relate increased ventricular forces to secondary ST–T changes.", "hypertrophy", "left_ventricular_hypertrophy", ["Abnormal depolarization and large ventricular forces can alter the recovery sequence.", "A compatible voltage/morphology context helps distinguish secondary strain from a primary ST–T process."], "Strain can mimic ischemia; the distinction is revisited after the learner masters primary/secondary repolarization in M8.", "M5 · secondary discordance; M7 · LVH/RVH", "M8 · primary versus secondary ST–T", "Which evidence strengthens an LVH-strain interpretation?", [choice("Compatible LVH voltage/forces with a matching secondary lateral ST–T pattern", true, "Correct—the depolarization context explains the recovery pattern."), choice("An isolated T-wave change without QRS context", false, "That is less specific."), choice("A normal calibration pulse proves strain", false, "Calibration validates measurement, not cause.")], "Require an explicit QRS-context explanation before the strain label."),
      scene("7.7", "Transfer", "Chamber evidence with confidence—not certainty", 7, "transfer", "Synthesize atrial, ventricular, progression, and repolarization evidence on an unannounced case.", "hypertrophy", "left_ventricular_hypertrophy", ["A defensible synthesis reports the criterion, supporting and conflicting evidence, plausible mimics, and confidence.", "A weak isolated criterion should not receive the same language as a coherent multi-lead pattern."], "The result becomes a mimic discriminator in M9 rather than a detached voltage fact.", "M2/M5/M7 · geometry, conduction, voltage, progression", "M8/M9 · repolarization and ischemia mimics", "What is the strongest synthesis when one LVH voltage criterion is present without corroboration?", [choice("Isolated LVH voltage criterion; limited specificity; correlate with context and other evidence", true, "Correct—precise and calibrated."), choice("Definite severe anatomical LVH", false, "The evidence cannot support that certainty."), choice("Acute coronary occlusion", false, "The voltage criterion does not establish that diagnosis.")], "Handoff separately to chamber-evidence Train, mixed Rapid, and an appropriate hypertension/structural-context case."),
    ],
  },
  {
    id: "repolarization-safety",
    order: 8,
    title: "Repolarization, QT, Electrolytes & Drugs",
    shortTitle: "Repolarization & QT",
    duration: "55–70 min · 4 resumable parts",
    outcome: "Measure and describe ST–T/QT features, understand rate correction and wide-QRS confounding, and perform a cautious medication/electrolyte safety review.",
    prerequisiteIds: ["ventricular-conduction"],
    prerequisiteLabel: "M5 activation and secondary ST–T change",
    accent: "#9a7a2f",
    scenes: [
      scene("7.0", "Activate", "Recovery follows activation", 3, "retrieve", "Reconnect J point, ST, T, QT, and QRS width.", "qt-qtc", "qt_interval", ["ST/T describe ventricular recovery after activation.", "An abnormal activation sequence can create secondary repolarization change."], "Primary-versus-secondary change must be considered before ischemia labels.", "M1 · normal ST/T; M5 · BBB/pacing", "Baseline and J point", "Why can LBBB alter the ST segment and T wave?", [choice("The changed activation sequence also changes recovery", true, "Correct—secondary repolarization follows abnormal depolarization."), choice("LBBB only changes atrial activation", false, "LBBB concerns ventricular activation."), choice("It proves acute infarction", false, "Secondary change is expected and complicates ischemia assessment." )], "Use a normal/LBBB paired trace."),
      scene("7.1", "Do", "Choose a baseline and find the J point", 5, "do", "Mark the reference baseline and QRS-to-ST junction.", "ischemia-st-t", "nonspecific_st_t_change", ["The TP segment is a common baseline reference; PR displacement and noise can complicate it.", "The J point is where QRS ends and ST begins."], "Bad reference selection can create a false millimeter measurement.", "M1 · calibration and normal template", "Describe ST/T shape", "What should happen before measuring ST displacement?", [choice("Choose a defensible baseline and identify the J point", true, "Exactly."), choice("Assume the screen center is zero", false, "The trace baseline must be identified."), choice("Read only the machine diagnosis", false, "Verify the waveform first." )], "Ask the learner to click both anchors and validate their visibility."),
      scene("7.2", "See", "Describe before assigning cause", 5, "see", "Characterize ST slope/distribution and T morphology.", "ischemia-st-t", "t_wave_inversion", ["Horizontal, downsloping, or upsloping ST depression and symmetric, biphasic, or inverted T waves are descriptions.", "Distribution and dynamics matter."], "The same shape can arise from ischemia, strain, conduction, drugs/electrolytes, or nonspecific change.", "M2 · lead distribution; M5 · secondary change", "QT measurement", "An isolated inverted T wave appears in one lead. What is the best first response?", [choice("Describe lead, morphology, and distribution, then compare context/prior", true, "Correct—one T-wave inversion is not a complete diagnosis."), choice("Call a heart attack immediately", false, "That overstates nonspecific evidence."), choice("Ignore calibration", false, "Calibration and quality remain relevant." )], "Answer the educational core of T-wave tangents directly, then return."),
      scene("7.3", "Do", "Measure QT without swallowing the U wave", 6, "do", "Choose a clear lead and mark QRS onset to T end across multiple beats.", "qt-qtc", "qt_interval", ["QT begins at QRS onset and ends at T-wave end.", "Tangent and threshold methods help when the end is ambiguous; U waves are not automatically included."], "A machine QTc should be checked when morphology or rate makes the endpoint uncertain.", "M1 · time calibration", "Rate correction", "Which interval should manual QT span?", [choice("P onset to QRS onset", false, "That is PR."), choice("QRS onset to the end of the T wave", true, "Correct."), choice("J point to P onset", false, "That does not define QT." )], "Report precision at the waveform sampling/box resolution, not false milliseconds."),
      scene("7.4", "Build", "QT changes with rate; corrections disagree", 6, "build", "Compare raw QT, Bazett QTc, and Fridericia QTc as rate changes.", "qt-qtc", "qtc_prolongation", ["QT shortens as rate rises.", "Bazett can overcorrect at fast rates and undercorrect at slow rates; formula choice and context matter."], "Medication decisions should not rest on a careless single corrected number.", "M3 · R–R interval", "Thresholds and wide QRS", "At an extreme heart rate, what is the safest interpretation of one Bazett QTc?", [choice("Treat it as exact and context-free", false, "Correction error grows at rate extremes."), choice("Verify measurement, consider an alternative correction, and state the method", true, "Exactly."), choice("Ignore the QT entirely", false, "QT can remain important; it needs careful interpretation." )], "If asked for formulas, teach them; the core scene remains conceptual and visual."),
      scene("7.5", "Discriminate", "When a wide QRS lengthens QT", 5, "discriminate", "Separate depolarization duration from recovery duration.", "qt-qtc", "qtc_prolongation", ["QT contains QRS plus recovery time.", "BBB/pacing can lengthen QT partly because depolarization is longer; reviewed approaches may consider JT."], "A raw prolonged QTc in BBB is not automatically equivalent to isolated delayed repolarization.", "M5 · QRS duration", "Drugs and electrolytes", "Why can QTc be misleading in a very wide QRS?", [choice("Part of the QT increase comes from longer depolarization", true, "Correct."), choice("QRS width never contributes to QT", false, "QT begins at QRS onset."), choice("Wide QRS always shortens recovery", false, "That is not a general rule." )], "Do not calculate an unsupported adjusted value without the governed method."),
      scene("7.6", "Connect", "Medication risk is a living evidence problem", 6, "connect", "Integrate QT measurement with medications, interactions, renal function, electrolytes, and repeat plans.", "qt-qtc", "electrolyte_drug_pattern", ["CredibleMeds separates known, possible, and conditional TdP risk; it is not a single ranked toxicity list.", "Drug lists change and commercial embedding requires license review."], "The clinically useful task is verify risk, identify modifiable contributors, and plan appropriate monitoring—not memorize a static list.", "M7 · verified QT/QTc", "Electrolyte patterns", "What is safest when a QT-active medication is considered?", [choice("Use an old memorized list as the only evidence", false, "The source is living and context matters."), choice("Verify the current source, measure carefully, and review interacting risks/electrolytes", true, "Correct."), choice("Stop every listed medication automatically", false, "Risk categories and patient context differ." )], "Never reproduce a copyrighted full drug list without licensing."),
      scene("7.7", "Transfer", "Electrolyte/drug pattern: hypothesis, not lab result", 7, "transfer", "Use ECG clues to request and integrate missing clinical data.", "qt-qtc", "electrolyte_drug_pattern", ["Potassium, calcium, magnesium, and drugs can alter P/QRS/ST/T/QT patterns.", "Patterns overlap and the current corpus lacks linked laboratory truth."], "A learner should say what to check next and why, not diagnose a serum value from the tracing.", "M7 · ST/T/QT description", "M8 · ischemia and mimics", "Peaked T waves and QRS widening raise concern for an electrolyte problem. What is the strongest next statement?", [choice("The exact potassium value is proven by ECG", false, "ECG cannot provide an exact serum concentration."), choice("This pattern warrants clinical correlation and urgent electrolyte testing in context", true, "Correct—hypothesis plus next datum."), choice("The pattern excludes drug effects", false, "Multiple contributors can overlap." )], "End with a medication-safety Clinical handoff only when its action rubric is reviewed."),
    ],
  },
  {
    id: "ischemia-infarction",
    order: 9,
    title: "Ischemia, Infarction, Territories & Mimics",
    shortTitle: "Ischemia & infarction",
    duration: "70–90 min · 5 resumable parts",
    outcome: "Describe and localize ischemic/infarction patterns, use contiguous/reciprocal and serial evidence, distinguish common mimics, and respect the acute-data boundary.",
    prerequisiteIds: ["leads-vectors", "ventricular-conduction", "chambers-voltage", "repolarization-safety"],
    prerequisiteLabel: "M2 territories + M5 conduction + M7 chamber/strain mimics + M8 ST/T description",
    accent: "#b0473c",
    scenes: [
      scene("8.0", "Activate", "A changed ST segment is a clue, not a diagnosis", 3, "retrieve", "Rebuild baseline, J point, contiguity, and secondary-change checks.", "ischemia-st-t", "myocardial_ischemia", ["Distribution, reciprocity, morphology, dynamics, and context determine concern.", "A nondiagnostic ECG does not exclude ACS."], "Chest-pain interpretation is an evidence-and-systems task, not a one-shape quiz.", "M2/M5/M7 · lead map and repolarization", "Injury-vector model", "What should be checked before calling ischemia from ST change?", [choice("Baseline/J point, contiguous distribution, reciprocal/dynamic evidence, and mimics", true, "Correct."), choice("Only whether one lead is above the screen center", false, "One uncalibrated isolated change is insufficient."), choice("The patient's troponin can be read from the ECG", false, "Troponin is separate clinical data." )], "Use the case packet for this tracing and general knowledge only for concept teaching."),
      scene("8.1", "Build", "Regional vectors create lead patterns", 6, "build", "Predict primary and reciprocal ST directions from an affected region.", "ischemia-st-t", "st_elevation", ["Regional electrical differences project toward some leads and away from others.", "Contiguous primary change with reciprocal change is more coherent than one isolated deflection."], "The vector model explains localization while avoiding rote territory cards.", "M2 · projection and opposite leads", "Territories", "If inferior leads show a coherent primary change, where might reciprocal evidence be sought?", [choice("High lateral leads such as I and aVL", true, "Correct—those provide an opposing frontal view."), choice("Only the lead-II rhythm strip", false, "A rhythm strip is not a full reciprocal territory assessment."), choice("Nowhere; reciprocity is impossible", false, "Reciprocal patterns can occur." )], "Do not invent a reciprocal change unless it is visible and grounded."),
      scene("8.2", "Do", "Measure distribution, not just millimeters", 6, "do", "Calibrate J-point measurement and apply versioned criteria cautiously.", "ischemia-st-t", "st_elevation", ["Thresholds differ by lead and demographic context, especially V2–V3.", "Morphology and dynamics add information beyond a binary threshold."], "Numeric criteria are living clinical content requiring clinician ownership and review date.", "M1 · calibration; M7 · J point", "Anterior/lateral and inferior patterns", "Two adjacent leads show concordant measured ST elevation, while a third isolated lead is noisy. Which evidence deserves more weight?", [choice("The coherent contiguous pattern in readable leads", true, "Correct—distribution and signal quality matter."), choice("The noisiest isolated lead", false, "Noise weakens that measurement."), choice("Whichever number the AI invents", false, "Measurements must be grounded to the trace." )], "The tutor may report only supplied measurements and visible segments."),
      scene("8.3", "See", "Anterior, lateral, inferior—and overlap", 6, "see", "Localize a pattern as a working territory description.", "mi-localization", "anterior_mi", ["Precordial and limb territories overlap; coronary anatomy varies.", "State the lead distribution before inferring a vessel."], "Localization accelerates communication and guides additional leads, but it is not a complete patient diagnosis.", "M2 · contiguous territories", "Posterior/right-sided views", "Changes in V2–V4 are best described first as what?", [choice("An anterior precordial distribution", true, "Correct—describe leads/territory before culprit speculation."), choice("Definite right-coronary occlusion", false, "The lead distribution does not prove that culprit."), choice("Inferior distribution", false, "Inferior leads are II, III, and aVF." )], "Highlight the contiguous leads only after the learner selects them."),
      scene("8.4", "Build", "Posterior and right-sided extensions", 6, "build", "Use mirror logic and additional leads when the standard 12-lead is incomplete.", "mi-localization", "posterior_mi", ["Posterior injury may appear as anterior reciprocal changes.", "V7–V9 and right-sided leads are additional recordings, not hidden standard leads."], "The right additional lead can clarify a clinically important extension.", "M2 · opposite views", "ST depression/T inversion", "Horizontal ST depression with tall R waves in V1–V3 raises what next-step consideration?", [choice("Posterior involvement and posterior leads, in the right context", true, "Correct—treat it as a concern to clarify."), choice("A normal finding by definition", false, "The combination can be significant."), choice("QT cannot be measured", false, "That is unrelated to the localization question." )], "Current data support may be demonstration-only; label simulated additional leads."),
      scene("8.5", "Discriminate", "Q waves, lost R progression, and established infarction", 6, "discriminate", "Apply Q-wave/distribution criteria without assigning timing from a single ECG.", "mi-localization", "pathologic_q_waves", ["Pathologic Q waves and loss of expected R progression can suggest prior infarction.", "Normal variants and lead placement can mimic both."], "A prior ECG and clinical history help separate old, new, and artifactual patterns.", "M2 · R-wave progression; M7 · morphology", "Mimic laboratory", "A new tracing has poor R progression but lead placement is uncertain. What is strongest?", [choice("Describe poor progression and verify placement/prior before calling infarction", true, "Exactly."), choice("Definite acute anterior MI", false, "Neither acuity nor cause is established."), choice("Ignore the finding", false, "It should be described and checked." )], "Do not use the report label to leak the answer before commitment."),
      scene("8.6", "Discriminate", "Mimic laboratory", 7, "discriminate", "Compare early repolarization, pericardial patterns, LVH/strain, BBB/pacing, electrolyte change, prior aneurysm, and lead error.", "ischemia-st-t", "myocardial_ischemia", ["Every target needs normal and near-mimic contrasts.", "Primary/secondary, focal/diffuse, reciprocal, dynamic, and context clues narrow the differential."], "Overcalling ischemia can harm; undercalling coherent dynamic change can also harm.", "M5/M7 · secondary and nonischemic change", "Serial comparison", "Which feature most strongly argues that ST–T change is secondary to LBBB?", [choice("A compatible LBBB QRS with expected discordant repolarization", true, "Correct—activation context explains the recovery pattern."), choice("The word 'ischemia' in a generic tutorial", false, "A title is not evidence."), choice("A normal narrow QRS", false, "That would not provide the LBBB mechanism." )], "Require explicit target–mimic discriminator before the label."),
      scene("8.7", "Transfer", "Serial change and the acute-data boundary", 8, "transfer", "Integrate prior/serial comparison while keeping chronic and acute mastery separate.", "mi-localization", "myocardial_infarction", ["Dynamic change can be more informative than one snapshot.", "PTB-XL is primarily resting/chronic; acute serial competence requires a validated acute source such as a reviewed STAFF-III ingest."], "The product must never turn a chronic record into a fake emergency STEMI case.", "M8 · territories and mimics", "M9 · chest-pain communication", "What can the current PTB-XL lane validly assess?", [choice("Recognition of supported resting/chronic patterns and established findings", true, "Correct."), choice("Dynamic acute evolution without serial recordings", false, "A single chronic record cannot show evolution."), choice("VF arrest management", false, "That requires a different telemetry/arrest corpus." )], "Show provenance and lock acute mastery until the correct data and review exist."),
    ],
  },
  {
    id: "integration-transfer",
    order: 10,
    title: "Integrated Interpretation & Clinical Transfer",
    shortTitle: "Clinical transfer",
    duration: "75–100 min · case-based chapters",
    outcome: "Perform, prioritize, and communicate complete ECG reads across clinic, ward, medication-safety, and ED contexts while stating uncertainty and data limits.",
    prerequisiteIds: ["rhythm-ectopy", "av-brady", "ventricular-conduction", "tachyarrhythmias", "chambers-voltage", "repolarization-safety", "ischemia-infarction"],
    prerequisiteLabel: "Objective-level readiness across M1–M9; informed override allowed",
    accent: "#2f6f69",
    scenes: [
      scene("9.0", "Activate", "Choose a framework; keep every domain", 4, "retrieve", "Map clerkship and HEARTS frameworks to the same complete read.", "integrated-interpretation", "normal_ecg", ["A framework is a memory scaffold, not the interpretation itself.", "Priority comes after a complete scan so an important finding is not missed."], "The final one-line synthesis should lead with what changes care and state uncertainty.", "M1 · systematic sweep", "Prioritization and synthesis", "Which is the best use of a framework?", [choice("A reproducible checklist that still allows clinical prioritization", true, "Correct."), choice("A replacement for looking at the tracing", false, "The framework organizes waveform evidence."), choice("A reason to list every finding as equally important", false, "Synthesis must prioritize." )], "Adapt terminology to the learner's chosen framework."),
      scene("9.1", "Explain", "Observation → interpretation → consequence", 6, "explain", "Separate what is seen, what it supports, confidence, and why it matters.", "integrated-interpretation", "normal_ecg", ["A strong claim cites lead, timing, or measurement.", "A consequence-bearing finding should not be buried after incidental details."], "Clear communication helps a supervisor verify and act on the evidence.", "M1–M8 · claim/evidence pairs", "Machine disagreement", "Which synthesis is strongest?", [choice("Abnormal ECG", false, "This gives neither evidence nor priority."), choice("Sinus rhythm at 64; wide QRS with RBBB morphology in V1/lateral leads; no confident acute ST–T claim", true, "This is specific, prioritized, and appropriately bounded."), choice("The machine is always right", false, "Machine statements require verification." )], "Grade evidence, completeness, priority, and clarity separately."),
      scene("9.2", "Discriminate", "Audit the machine read", 6, "discriminate", "Accept, revise, or reject automated statements using visible evidence.", "integrated-interpretation", "normal_ecg", ["Computer measurements can help; diagnostic statements still need over-reading.", "A disagreement should be resolved at the relevant lead/interval, not by authority alone."], "Machine overread/underread is a real clinical task and a strong advanced-learning interaction.", "All prior modules", "Clinic/ward cases", "The machine says 'anterior infarct' but the only clue is poor R progression with high V1/V2 placement. What is best?", [choice("Accept the machine without review", false, "The placement concern weakens the claim."), choice("Describe poor progression, correct/verify placement, and compare a prior before accepting infarct", true, "Exactly."), choice("Delete the ECG", false, "The tracing should be reassessed, not discarded blindly." )], "Require a proof-on-trace click and explanation before scoring the audit."),
      scene("9.3", "Transfer", "Palpitations: fast first, complete second", 7, "transfer", "Use a compact priority response, then a full rhythm interpretation.", "af-flutter", "atrial_fibrillation", ["The rapid response asks stability + regularity/width + dominant rhythm concern.", "The untimed debrief adds atrial evidence, rate, differential, and context."], "This separates emergency prioritization from typing speed.", "M3/M6 · rhythm ladder and tachy matrix", "Syncope/bradycardia", "In a 20-second quick-look, what answer construct is fairest?", [choice("Six free-text sweep fields plus sixteen tags", false, "That mostly measures input speed."), choice("One dominant rhythm/priority category plus confidence", true, "Correct; full reasoning follows after commitment."), choice("No ECG response at all", false, "A focused quick-look can be assessed." )], "Keep the tutor silent until commitment."),
      scene("9.4", "Transfer", "Syncope: conduction plus perfusion", 7, "transfer", "Integrate P–QRS pattern, escape, symptoms, medications, and uncertainty.", "pr-av-block", "av_block_third_degree", ["A complete ECG description is necessary but not sufficient for a syncope decision.", "Medication and symptom timing can be requested as staged data."], "Clinical cases should test ECG recognition separately from management so one cannot inflate the other.", "M4/M5 · AV and ventricular conduction", "Medication safety", "A stem explicitly states 'complete heart block' before showing the ECG. Should a management answer raise ECG-recognition mastery?", [choice("Yes, automatically", false, "The tested finding was disclosed, so recognition was not demonstrated."), choice("No; score management separately from ECG evidence", true, "Correct."), choice("Only if the learner clicks randomly", false, "Recognition needs valid evidence." )], "Preserve separate competency axes in the debrief."),
      scene("9.5", "Transfer", "QT-active medication review", 7, "transfer", "Measure, verify, identify confounds, and choose a reviewed monitoring/action category.", "qt-qtc", "qtc_prolongation", ["Manual measurement, formula, QRS width, medications, renal function, electrolytes, and prior ECG all matter.", "A current licensed drug-risk source is required."], "This is the clearest bridge from ECG measurement to medication safety.", "M7 · QT workflow", "Chest pain and serial comparison", "The machine QTc is high in a paced wide QRS. What comes next?", [choice("Verify the measurement and account for wide-QRS confounding before a decision", true, "Correct."), choice("Treat the printed QTc as context-free truth", false, "Pacing and QRS duration matter."), choice("Ignore medications and electrolytes", false, "They are essential contextual risks." )], "The model can explain; deterministic policy and clinician-reviewed rules govern the action score."),
      scene("9.6", "Transfer", "Chest pain without fake acuity", 7, "transfer", "Prioritize calibration, serial/prior comparison, territory/mimic evidence, and escalation.", "mi-localization", "myocardial_infarction", ["A single resting chronic record cannot prove dynamic acute change.", "A nondiagnostic ECG does not exclude ACS."], "The acute lane remains visibly locked until validated serial/acute data are present.", "M8 · ischemia and data boundary", "Communication", "What should a chronic PTB-XL case be labeled as?", [choice("A real resting ECG for supported interpretation practice", true, "Correct—honest provenance."), choice("A live evolving STEMI without serial evidence", false, "That would be fabricated context."), choice("A VF telemetry strip", false, "The recording type is different." )], "Use authored context only when it is visibly separated from recorded patient provenance."),
      scene("9.7", "Connect", "Present, remediate, and return", 8, "connect", "Communicate a one-line read and turn each error into an exact learning loop.", "integrated-interpretation", "normal_ecg", ["A concise handoff includes context, rate/rhythm, priority findings, comparison, concern, and uncertainty.", "End-of-shift remediation links to the specific scene/subskill, then returns for an equivalent transfer case."], "The platform becomes adaptive when errors change what is taught next—not when AI merely comments afterward.", "M1–M9 · complete evidence chain", "Personalized mixed Rapid and Clinical shifts", "After repeated RBBB/LBBB confusion, what is the best next sequence?", [choice("Show the same labeled RBBB indefinitely", false, "Blocked repetition alone creates cueing."), choice("Return to the terminal-force scene, then target/mimic/normal Train, then delayed mixed transfer", true, "Exactly—the loop repairs mechanism and tests discrimination."), choice("Raise mastery because the learner spent more time", false, "Time-on-task is not competence." )], "Finish with explicit links to the exact remedial scene, Train deck, Rapid transfer, and Clinical case."),
    ],
  },
];

export const GUIDED_MODULE_BY_ID = new Map(GUIDED_MODULES.map((module) => [module.id, module]));
